### ISSUE TITLE
``mod`` for arrays

### ISSUE THREAD

**Issue by czgdp1807** [lcompilers/lpython#1035]
@certik Builtin `%` in LPython doesn't work on arrays by default because it is implemented as a function and not a `binop`. So the question is which approach to follow,
1. To make `_mod` function defined in `lpython_builtin.py` vectorised;
2. Define `Mod` as `binop` and then use `builder->CreateSRem` in LLVM backend. Note that not all backends might support modulus operation on types other than integers.
3. Define [`mod`](https://numpy.org/doc/stable/reference/generated/numpy.mod.html) and then make it vectorisable.

I think 3rd approach is a good one and complies with Python and NumPy standards. What do you say @certik?

_Originally posted by @czgdp1807 in https://github.com/lcompilers/lpython/pull/1002#discussion_r951450426_

**Comment by certik** [comment]
If the third approach works, we can go with that I think. Otherwise we can do 1., or 2.
