### ISSUE TITLE
Using `.lpy` as extension instead of `.py` 

### ISSUE THREAD

**Issue by Smit-create** [lcompilers/lpython#105]
I am thinking that we should use `.lpy` as the extension for `lpython` files. The main reason is that after supporting import statements we will have python interpreter error like:
```
+ integration_tests/test_math
+ python integration_tests/py_test_math.py
Traceback (most recent call last):
  File "/home/admin-pc/Smitlunagariya/lpython/integration_tests/py_test_math.py", line 5, in <module>
    from modules_math import factorial
  File "/home/admin-pc/Smitlunagariya/lpython/integration_tests/modules_math.py", line 1, in <module>
    def factorial(x: i32) -> i32:
NameError: name 'i32' is not defined
```

**Comment by certik** [comment]
I think we should use regular `.py` files. Those `i32` must be imported from LPython's runtime library such as `from ltypes import i32`.

**Comment by Smit-create** [comment]
Yeah, that also sounds appropriate to me.

**Comment by Smit-create** [comment]
This can be closed now.
