### ISSUE TITLE
stod Exception: "Out of range" for very small floating point number

### ISSUE THREAD

**Issue by Thirumalai-Shaktivel** [lcompilers/lpython#1088]
```py
4.94e-324
```
```console
$ lpython examples/expr2.py --show-tokens
std::exception: stod
$ lpython examples/expr2.py --show-ast --tree  
std::exception: stod
$ lpython examples/expr2.py --show-ast --tree --new-parser
std::exception: stod
```

**Comment by czgdp1807** [comment]
I think one cannot below `1.7e-308` for floating points. Doing, `4.94e-324/1.7e-308` gives, `2.9062685049485084e-16` in Python.

**Comment by Thirumalai-Shaktivel** [comment]
Yup, there is a limit from `DBL_MAX = 1.79769e+308` to `DBL_MIN = 2.22507e-308` (https://en.cppreference.com/w/cpp/types/climits)

**Comment by Thirumalai-Shaktivel** [comment]
I think we can use [stold](https://cplusplus.com/reference/string/stold/)

**Comment by czgdp1807** [comment]
I don’t think that will work. long double same as double in many machines. The max I know of is 128 bit floating points but they are rare AFAIK.

**Comment by certik** [comment]
I would just use `std::strtod`, there is an example here how to check for errors: https://en.cppreference.com/w/cpp/string/byte/strtof
