### ISSUE TITLE
Supporting ``Enum`` and ``Union`` in LPython

### ISSUE THREAD

**Issue by czgdp1807** [lcompilers/lpython#1113]
As the title says, we need to figure out a good syntax for ``Enum`` and ``Union`` in LPython, especially in the C backend.

For syntax we can follow the same as of CPython,

- [x] ``enum`` - https://docs.python.org/3/library/enum.html - https://github.com/lcompilers/lpython/pull/1117
- [x] ``Union`` - Import from CTypes, see https://stackoverflow.com/a/45384034 - https://github.com/lcompilers/lpython/pull/1126

Implementation in C backend is fairly easy. For LLVM we can figure it out as well (just use structs or something else) but a low priority for LLVM backend.

**Comment by czgdp1807** [comment]
@certik @rebcabin @ronnuriel Please let me know if you agree with this syntax. Then we can start implementing things in C backend.

**Comment by rebcabin** [comment]
Regarding `enum`, the URL points to good candidate tests for the facility. So long as the same code works identically in CPython and LPython (including the import statements), I think it's good. Will comment on Union shortly

**Comment by czgdp1807** [comment]
Cool I will start off with `enum` implementation then. I think the same syntax as CPython is fine.

**Comment by rebcabin** [comment]
I approve of the `Union` proposal, too.

**Comment by rebcabin** [comment]
remember the overriding tenet is 100% compatibility with ordinary CPython, a specific version x.y.z if necessary to limit it.

**Comment by czgdp1807** [comment]
Sure. Makes sense. So I will go ahead and implement both Union and Enum in C according to our priorities discussed offline.

**Comment by czgdp1807** [comment]
Can we close this? As the initial versions are already in. Please let me know. I am attaching `could close` label for now.

**Comment by certik** [comment]
I think so. I am sure there will be tons of things to improve, but let's simply open up issues as we discover them. The initial implementation is done. Thanks @czgdp1807 !
