### ISSUE TITLE
Support C tests

### ISSUE THREAD

**Issue by ronnuriel** [lcompilers/lpython#1114]
As the title say, tests to support:
- [x] test_builtin_pow
- [x] test_builtin_str
- [x] test_builtin_oct
- [x] test_builtin_hex
- [x] test_builtin_divmod
- [ ] test_math_02
- [x] test_cmath
- [x] test_complex
- [x] test_unary_plus

**Comment by certik** [comment]
I created https://github.com/lcompilers/lpython/issues/2076 for `test_math_02` which doesn't work yet.
