### ISSUE TITLE
C backend - Static Functions 

### ISSUE THREAD

**Issue by ronnuriel** [lcompilers/lpython#1115]
Need to add support to C backend for static functions.

**Comment by certik** [comment]
@czgdp1807  Here is a good issue for you. We should probably do it with a `@static` decorator.

**Comment by czgdp1807** [comment]
On it. Will work on array programming and this concurrently.

**Comment by czgdp1807** [comment]
I think this would only matter in C backend. LLVM doesn't have any notion of static functions as far as I know.

**Comment by certik** [comment]
What exactly is a static function?

**Comment by czgdp1807** [comment]
https://stackoverflow.com/a/558132 - A function visible only in the translation unit where it is defined.

**Comment by certik** [comment]
So we need to implement this in LLVM too, currently all global functions are visible outside. Static functions would somehow not be possible to call from other units. Is this achieved with name mangling, or how is that achieved?

**Comment by czgdp1807** [comment]
> Static functions would somehow not be possible to call from other units. Is this achieved with name mangling, or how is that achieved?

I think it can be handled at ASR level. If a function is static and is defined in a different translation unit but called in a another translation unit then raise semantic error. AFAIK, C compiler also handles them in the frontend level.

**Comment by certik** [comment]
I see. So we add some "static" flag to ASR functions, then add some semantic checks (possibly later) and in the C backend we honor this flag.

**Comment by czgdp1807** [comment]
Yes I think. LLVM should never be concerned. It should just generate correct LLVM code for the translation unit it receives. Note that static functions can be imported and then they are visible to the file where they are imported to. Similar is the case with C static functions like if it is defined in a header and that header is included in some other file then it is visible in that file as well.
