### ISSUE TITLE
Implement goto statement in C backend

### ISSUE THREAD

**Issue by ronnuriel** [lcompilers/lpython#1116]
As the title says, we need to implement goto statement and add a support in c backend.

goto syntax - `https://github.com/snoack/python-goto`

**Comment by ronnuriel** [comment]
@certik Will you be taking care the ASR side?

**Comment by certik** [comment]
The ASR side is already implemented, see the `GoTo` and `GoToTarget` nodes and the associated documentation.

**Comment by certik** [comment]
So we just need to implement the visitors in the C backends for these two nodes and it will work.

Then we need to settle on some syntax in Python that hopefully works with standard Python (CPython) also, and produce the `GoTo` and `GoToTarget` ASR nodes.
