### ISSUE TITLE
visit_StringItem bug -C backend

### ISSUE THREAD

**Issue by ronnuriel** [lcompilers/lpython#1124]
C backend bug when trying to access to a negative position in string
can be fund in file test: integration_tests/test_str_01.py in function: test_str_index

Example : 
```
    a: str
    a = "012345"
     assert a[-1] == "5"
```
Quick fix offer will be : 
   ```
void visit_StringItem(const ASR::StringItem_t& x) {
        this->visit_expr(*x.m_idx);
        std::cout << "LETF IS = " + src << std::endl;
        std::string new_idx = src;
        //removes "  + 1"
        new_idx = new_idx.pop_back();
        new_idx = new_idx.pop_back();
        new_idx = new_idx.pop_back();
        new_idx = new_idx.pop_back();

        if(std::stoi(new_idx) >0 ) {
            new_idx = src;
        } else {
            new_idx = "len(+" + new_idx + ") + 1";
        }
```
But please check ASR

**Comment by certik** [comment]
This is related to https://github.com/lcompilers/lpython/pull/1099. I think we should not handle negative indices in the backend for performance reasons, but rather in the frontend. See my comment here: https://github.com/lcompilers/lpython/pull/1099#discussion_r969782446 for more details.
