### ISSUE TITLE
Bug in `for` with negative step

### ISSUE THREAD

**Issue by Smit-create** [lcompilers/lpython#1153]
Python code:
```py
def f():
    i: i32
    for i in range(5, 0, -1):
        print(i)

f()
```

LPython Output:
```
% lpython a.py && ./a.out         
5
4
3
2
1
0
-1
```

CPython:
```
% python a.py                    
5
4
3
2
1
```

**Comment by Smit-create** [comment]
I think the best way to fix this might be to just change this line:
https://github.com/lcompilers/lpython/blob/91cb772ef86a58d8b5020a8dde864754bc06d06a/src/lpython/semantics/python_ast_to_asr.cpp#L3680

To do addition instead of subtraction when we have a negative compile time value in `increment`?

**Comment by certik** [comment]
Try it. We can then polish the fix if it is not the right one.

**Comment by czgdp1807** [comment]
> To do addition instead of subtraction when we have a negative compile time value in `increment`?

I think compile time value is not the only concern. What if three of start, step and end all are runtime variables. Seems like are always adding `-1` to the end. I think a proper way would be to add the sign of end to stop. That should do the job. If its available at compile time then we already know that its either `+1` or `-1`. Basically its simply, `offset = (step >= 0) * 1 + (step < 0) * (-1)`, then `end = end + offset`. With large number of iterations the overhead won't be that high since we only offset `end` before we start the loop.

**Comment by certik** [comment]
ASR loop correctly supports increasing or decreasing iterations. All we need is to just generate correct ASR for the code above.

**Comment by czgdp1807** [comment]
By ASR loop you mean `do_loop` pass, right? Probably for loops as well we need to test 216 cases, each of the start, end and step can be,

1. Compile time positive.
2. Runtime positive.
3. Compile time negative.
4. Runtime negative.
5. Compile time 0.
6. Runtime 0.

So, 6 x 6 x 6 = 216 cases. We need to make sure each of these cases work as desired. Loops are important so proper testing of these is very important.

**Comment by certik** [comment]
I mean the `DoLoop` node.

**Comment by Smit-create** [comment]
> So, 6 x 6 x 6 = 216 cases. We need to make sure each of these cases work as desired. Loops are important so proper testing of these is very important.

Python doesn't allow step to be 0:
Traceback (most recent call last):
```py
  File "/Users/thebigbool/repos/lpython/a.py", line 36, in <module>
    f()
  File "/Users/thebigbool/repos/lpython/a.py", line 11, in f
    for j in range(start[a], stop[b], 0):
ValueError: range() arg 3 must not be zero
```

Moreover, in the LLVM backend, we only support Integer Constants.

**Comment by czgdp1807** [comment]
Great. That reduces the number of cases to 64 + 1 (error for 0) which is cool. 

> Moreover, in the LLVM backend, we only support Integer Constants.

Please open an issue for it. We should support variable arguments as well for each of start, step and stop. Not necessarily to be done in this PR
