### ISSUE TITLE
Provide a function analogous to ``sizeof`` in C language

### ISSUE THREAD

**Issue by czgdp1807** [lcompilers/lpython#1176]
Sometimes we need to pass the output of `sizeof` to C interoperable functions and hence we need to provide an intrinsic `sizeof` function. Consider the following example,

```python
@dataclass
class A:
    x: i32
    y: i64
    .
    .
    and so on


@ccall
def cmalloc(bytes: i64) -> CPtr:
    pass

def call_malloc():
   x: CPtr = cmalloc(sizeof(A) * 20)
```

**Comment by rebcabin** [comment]
This might be a good feature, but surely SWIG and other Python-C FFIs do something similar. Do we really need to innovate a design, or can we copy the predecessors? I'm ok with new designs if the old ones stink, but, in general, I want to avoid piling on innovations. This is a judgment call.

**Comment by certik** [comment]
In terms of new features here, the only new feature is the `SizeOfType(ttype type)` ASR node, which returns the size in bytes of the given type (such as a struct).

It is a compile time feature, but is backend specific (like the implementation of all other ASR nodes), so the backend will choose some memory representation of the given type, and then `SizeOfType` will return the actual size of this, at compile time.
