### ISSUE TITLE
ListSection is not implemented in the LLVM

### ISSUE THREAD

**Issue by Thirumalai-Shaktivel** [lcompilers/lpython#1177]
```py
def test():
    x: list[i32] = [1, 2, 3]
    print(x[1:2])

test()
```
cc @czgdp1807

**Comment by Thirumalai-Shaktivel** [comment]
How do I implement this?
- Implement the visit function in LLVM: Create a new list and copy the section and return?
- Implement ASR Pass as we did for List concat?

**Comment by czgdp1807** [comment]
> * Implement ASR Pass as we did for ListConcat?

This is good enough for me. 

P.S. There must be a way to implement all such high level list features in the same ASR pass so that we reduce the constant overhead and code size of passes. Can you try to figure it out and let us know here?

**Comment by Thirumalai-Shaktivel** [comment]
I will rename `pass_list_concat` -> `list_asr_pass`, and add the list related ASR passes there.
That might work.
I will create a PR and ping you there.
