### ISSUE TITLE
Rename EnumMember -> EnumClassMember

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#1183]
I would still do `EnumClassMember`. I think the class and instance relationship is well established and people understand it. I had to lookup our discussion to figure out what `EnumMember` means.

Essentially, `Struct`, `Enum`, `Union`, etc. they all have a "class" and "instance" and one can access both (with different semantics and consequences). If we don't like the term "class" then let's figure out a different word, to make this clear.

**Comment by certik** [comment]
I would probably use the terms `Class` and `Instance`: https://en.wikipedia.org/wiki/Class-based_programming, it seems that is what we are currently doing in ASR. It doesn't mean these are the only paradigms we support, but right now that is what maps into Python and Fortran usage.

**Comment by czgdp1807** [comment]
My only concern is with `StructClassMember`. `Struct` and `Class` are two different concepts in C/C++ and hence might confuse developers. `EnumClassMember`, `UnionClassMember` is fine by me. `Static` might also become an alternative such as `StaticStructMember`, `StaticEnumMember`, etc.

**Comment by certik** [comment]
I think `Static` is fine. I think it should start with `Struct` and `Enum`, to have all the relevant nodes next to each other. So `StructStaticMember` and `EnumStaticMember`.
