### ISSUE TITLE
Extend LocationManager to handle multiple files

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#1218]
Currently we can convert the linear location information (start/end) to a file + line + column number, but it only works for one file. We need to extend this mechanism to multiple files (since a Python program typically imports multiple files).

To do that, the LocationManager simply "concatenates" all the files, and then the linear index is pointing into this concatenated stream. So we store a list of start indices for each file, then bisect it to obtain the file (filename) and then within this file we remap as we do now to obtain line + column numbers.

**Comment by Shaikh-Ubaid** [comment]
I am looking at this issue for some time. I would like to work on this. Shall I give it a try @Thirumalai-Shaktivel ?

**Comment by Thirumalai-Shaktivel** [comment]
I didn't start working on this issue.
>  I would like to work on this. Shall I give it a try @Thirumalai-Shaktivel ?

Sure, that would be very helpful.

**Comment by Shaikh-Ubaid** [comment]
Thank you!

**Comment by Shaikh-Ubaid** [comment]
I have the following doubts, please possibly clarify.

https://github.com/lcompilers/lpython/blob/d4a6d5360ca520d9a25d658e6660cb39a2eda4e2/src/libasr/location.h#L97-L98
1. What is the difference between output code and original code? Why could we not directly use the original code for storing positions?

https://github.com/lcompilers/lpython/blob/d4a6d5360ca520d9a25d658e6660cb39a2eda4e2/src/libasr/location.h#L182-L183
2. Where do we populate the values for the `out_start` and `in_start` variables?
3. Also, could someone possibly break down this issue into smaller sub-parts or share some hints about solving this, please?

**Comment by Thirumalai-Shaktivel** [comment]
After thinking on this issue, I came to the conclusion that instead of concatenating all the files, ...
Why not simply print the error message in `compile_module_till_asr()` (since all the imported files are compiled till asr), along with the current file Semantic error, something like this:
```py
semantic error: Type mismatch in annotation-assignment, the types must be compatible
 --> /home/thirumalai/Open_Source/lpython/src/bin/../runtime/expr.py:3:1
  |
3 | e: i32 = 1.1
  | ^        ^^^ type mismatch ('i32' and 'f64')


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).

semantic error: The file '/home/thirumalai/Open_Source/lpython/src/bin/../runtime/expr.py' failed due to semantic error
 --> examples/expr2.py:1:1
  |
1 | from expr import e
  | ^^^^^^^^^^^^^^^^^^ 


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```
@certik @Shaikh-Ubaid What do you think?

**Comment by Thirumalai-Shaktivel** [comment]
Nested import would like this:
```py
syntax error: Token '"B"' (of type 'string') is unexpected here
 --> integration_tests/test_import/test_import_1.py:5:13
  |
5 |     return 1"B"
  |             ^^^ 


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).

semantic error: The file 'integration_tests/test_import/test_import_1.py' failed to parse
 --> integration_tests/test_import/__init__.py:1:1
  |
1 | from .test_import_1 import print_a, print_b
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).

semantic error: The file 'integration_tests/test_import/__init__.py' failed due to semantic error
 --> integration_tests/test_import_01.py:1:1
  |
1 | import test_import
  | ^^^^^^^^^^^^^^^^^^ 


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```

**Comment by Shaikh-Ubaid** [comment]
I am working on this issue. I probably need some more time, please.

**Comment by Shaikh-Ubaid** [comment]
Also, I came across this

**Code:**
```python
def main0():
    x: i32
    x = 3.14
    y:i32
    y = 2.1
    z: i32
    z = -3.0
    print(x)
    print(y)
    print(z)

main0()
```
**Output:**
```
(lp) ubaid@ubaid-Lenovo-ideapad-330-15ARR:~/OpenSource/lpython$ lpython examples/expr2.py
semantic error: Type mismatch in assignment, the types must be compatible
 --> examples/expr2.py:4:5
  |
4 |     x = 3.14
  |     ^   ^^^^ type mismatch ('i32' and 'f64')


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed). 
```

During our last meet, Ondrej discussed that `lpython` (like other compiler's usually do) should detect (and print) all the compilation errors in all the files (the `main module` file + other imported files). In the above example, we see that there are three `semantic` (type mismatch) errors, but `lpython` at present detects only one. Please, could someone possibly share if this is desirable or if it is a bug or a feature yet to implemented/supported?

CC: @certik

**Comment by Shaikh-Ubaid** [comment]
>To do that, the LocationManager simply "concatenates" all the files
>Please, could someone possibly share if this is desirable or if it is a bug or a feature yet to implemented/supported?

With respect to the above [comment](https://github.com/lcompilers/lpython/issues/1218#issuecomment-1312710513), at present, it seems that even if the `LocationManager` concatenates all the files, the compilation would stop at the first error captured (in the `main module` or in one of the `imported` files).

**Comment by Thirumalai-Shaktivel** [comment]
https://github.com/lcompilers/lpython/issues/1218#issuecomment-1312710513
This feature would be very useful, and yes, this yet and has to be implemented.

But, I think [here](https://github.com/lcompilers/lpython/issues/1218#issue-1416996968) @certik is talking about something like the following. Consider an example:
a.py
```py
i: i32 = 3.142
```
b.py
```py
from a import i
j: i32 = i
```
c.py
```py
from b import j
print(j)
```
So, here we have to push_back or concatenate all the filename to a `vector`(with location, I think). 
_|_
|--|--
_|_
a.py| 1 <--
b.py| 1
c.py| 1
stack|loc

From the above example, there is an error in `a.py`. Now, Print the error message along with the other file pointing to it.
It would look like this:
```py
semantic error: Type mismatch in assignment, the types must be compatible
 --> a.py:4:5
  |
1 |     i: i32 = 3.142
  |     ^        ^^^^^ type mismatch ('i32' and 'f64')
Imported here:
 --> b.py:1:1
  |
1 | from a import i
  | ^^^^^^^^^^^^^^^
Imported here:
 --> c.py:1:1
  |
1 | from b import j
  | ^^^^^^^^^^^^^^^ 
```

**Comment by Thirumalai-Shaktivel** [comment]
> I am working on this issue. I probably need some more time, please.

Yup, take your time. Also, please any doubts you have.

**Comment by Shaikh-Ubaid** [comment]
Thank you for the clarification, Thirumalai. It seems the situation you shared here https://github.com/lcompilers/lpython/issues/1218#issuecomment-1312746742 is (to some extent) partially supported by the current `lpython`. I attempted to (hopefully) improve it in https://github.com/lcompilers/lpython/pull/1294, but it did not need to modify the `LocationManager` to support it.

I am slightly confused about the aim of this issue. This issue is titled `Extend LocationManager to handle multiple files`, indicating we should/would be needing to modify the `LocationManager` (since we need to extend it). At the same time, if we attempt to support the situation in https://github.com/lcompilers/lpython/issues/1218#issuecomment-1312746742, it seems we could support it without modifying the `LocationManager`.

**Comment by Shaikh-Ubaid** [comment]
https://github.com/lcompilers/lpython/blob/ce4612d5d2a7207ab8147bb102e39bbbe5e67e2c/src/lpython/semantics/python_ast_to_asr.cpp#L242-L263

Everytime `compile_module_till_asr()` is called, a new object of `LocationManger` is created (Line 27 in the above code).

Currently, each object of `LocationManger` has access to a single file. There is no object of `LocationManager` which has access to all (imported) file names or all (imported) files contents. Thus, for any given (single) object of `LocationManager`, it is not being possible to concatenate all the files as it does not have access to them.

**doubts:**

>To do that, the LocationManager simply "concatenates" all the files,
1. Please, could someone possibly share how we should/could support concatenation of all files (and maintain a list of file names and their starting indices)? Do we need to use `static` member variables in `LocationManager`? If we used static members, the information about all the `file` names and their contents would be available with the whole Class (everytime an object of `LocationManger` is provided with a file name/content, the Class could store the file name/content in the static member and thus the information would be available for later use).

>and then the linear index is pointing into this concatenated stream.
2. Currently, every imported file is processed individually. Thus, the index available to us is with respect to the (single) imported file. If we managed to support storing (and accessing of) all the file names and their contents, how (or from where) would a linear index pointing into the concatenated stream be available to us?
