### ISSUE TITLE
Import nested modules

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#1280]
It is a high priority for us to be able to get the following imports working:
```python
from A.B.C.D import x
from A.B.C.E import y
```

**Comment by certik** [comment]
Now when #1281 is in, what remains to be done?

I'll test it soon with our production code and see if anything remains. One thing that we need is finding these nested modules using the `-I` flag. I don't know if this works already or not yet.

**Comment by Thirumalai-Shaktivel** [comment]
The following doesn't work
```console
$ pwd
/home/thirumalai
$ lpython -I /home/thirumalai/Open_Source/lpython integration_tests/test_import_01.py
$
```
I will try to debug and report back.

**Comment by certik** [comment]
The use case we have is `lpython a.py` and in `a.py` we do `from A.B.C.D import x`, where the package `A` lives somewhere completely else and have to specify the path using `-I`.

**Comment by Thirumalai-Shaktivel** [comment]
The following work:
```console
(lf) ➜  $ pwd
/home/thirumalai
(lf) ➜  $ cat a.py                                
import test_import
from test_import import print_a

print(print_a())
print(test_import.print_b())
print(test_import.print_c())
(lf) ➜  $ lpython -I /home/thirumalai/Open_Source/lpython/integration_tests a.py
A
B
C
```
The nested modules has the following error:
```console
$ lpython -I /home/thirumalai/Open_Source/lpython/integration_tests a.py             
semantic error: Could not find the module '__init__.py'. If an import path is available, please use the `-I` option to specify it
 --> a.py:1:1
  |
1 | from test_import.import_module_01 import multiply, e
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```
I will debug and report back

**Comment by certik** [comment]
@Thirumalai-Shaktivel this now works, doesn't it?

**Comment by Thirumalai-Shaktivel** [comment]
Yup, It works. I just added the comment to keep track of all the import issues.

**Comment by certik** [comment]
I am going to close this one then.
