### ISSUE TITLE
Importing modules does not work inside the function

### ISSUE THREAD

**Issue by Thirumalai-Shaktivel** [lcompilers/lpython#1317]
I came across another issue that doesn't work yet. Like for this example:
```py
import test_import

def test():
    print(test_import.print_a())
    print(test_import.print_b())
    print(test_import.print_c())

test()
```
Error:
```console
lpython integration_tests/test_import_01.py
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/thirumalai/Open_Source/lpython/src/bin/lpython", in _start()
  File "./csu/../csu/libc-start.c", line 392, in __libc_start_main_impl()
  File "./csu/../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main()
  File "/home/thirumalai/Open_Source/lpython/src/bin/lpython.cpp", line 1545, in ??
    err = compile_python_to_object_file(arg_file, tmp_o, runtime_library_dir, lpython_pass_manager, compiler_options, time_report);
  File "/home/thirumalai/Open_Source/lpython/src/bin/lpython.cpp", line 592, in ??
    !(arg_c && compiler_options.disable_main), infile);
AssertFailed: asr_verify(*tu, true, diagnostics)
```
I will try to work on this later this week. After that, I think we are ready to start making python packages.

_Originally posted by @Thirumalai-Shaktivel in https://github.com/lcompilers/lpython/issues/1305#issuecomment-1321485441_

**Comment by certik** [comment]
We have two options:

* Handle it in the frontend, so `test_import.print_b()` just becomes an ExternalSymbol to the correct `print_b()` and the information that it was called via `test_import.` will be lost.
* Add `test_import` as a symbol into the SymbolTable.

The second approach is more general, it would allow to treat modules as symbols / variables. Not sure if we need it or not.

@czgdp1807 what is your opinion?

**Comment by certik** [comment]
Regarding priorities, this is nice to have, but not critical, as we can simply import the symbols directly.

**Comment by czgdp1807** [comment]
Oh yes. I am fixing this exact issue. I think we follow second approach right now. But for the case with function defined inside a module has the same name as the module then second approach will be messier because you will have to do name mangling. See `mathfn` for example, `mathfn/sin.py` is a module which has `def sin` defined inside it. So here first approach is an easy to follow option. However where this same name case is not present then second approach is easier.

**Comment by certik** [comment]
I would work on this later, I think first we should implement more examples, such as making mathfn much more complex and see what else is missing. Then we can do this one in a more natural manner.
