### ISSUE TITLE
Feature request: an equivalent of "char        buffer[64];" in a struct

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#1333]
Right now if you do:
```
@dataclass
class some_struct:
    buffer: i8[64]
```
It will produce an array with a descriptor. But rather, we need it to produce `char buffer[64]`, that is, 64 bytes of memory. It could be that we can use a descriptor by default, but if we do:
```
@ccallable
@dataclass
class some_struct:
    buffer: i8[64]
```
Then it would use the array directly.

**Comment by czgdp1807** [comment]
For both C and LLVM backends, correct? And specifically for `i8` type?

**Comment by certik** [comment]
Yes, I would always do it for the LLVM backend to ensure the design is good. This we also need for the C backend. Yes, we need it for i8, and if we needed larger ones later, I think we could "emulate" them using i8.

**Comment by certik** [comment]
This is now a pretty high priority, we need to figure out a fix.

**Comment by czgdp1807** [comment]
The underlying issue is https://github.com/lcompilers/lpython/issues/1350. If we figure out a decent protocol then solving this issue is a by-product.

**Comment by certik** [comment]
The issue #1350 is general, and we need to figure out a solution.

In the meantime to unblock us, the issue is actually quite simple. Regular struct I think should not be BindC and we should have the freedom to rearrange or represent members (arrays) any way we like. In this particular case, when interoperability with C is needed, we should declare it as:
```
@ccallable
@dataclass
class some_struct:
    buffer: i8[64]
```
And then declare all members, such as `buffer`, as BindC. This then in return prescribes that it must be represented by a pointer, and in this case the memory is in the struct itself, 64 bytes, just like in C.

**Comment by czgdp1807** [comment]
Makes sense. Will do so, once I come back from vacation.
