### ISSUE TITLE
Runtime do loop increment in C backend

### ISSUE THREAD

**Issue by czgdp1807** [lcompilers/lpython#1392]
Right now one can only have compile time constants as increment values of do loop. The reason is simple. The choice of comparison operator depends on the sign of increment (see the code snippet below). If the increment value is available only at runtime then we can't figure out the comparison operator to be inserted in the C code.

https://github.com/lcompilers/lpython/blob/b47f2e8627aede075194836dc177269cc0b8ce98/src/libasr/codegen/asr_to_c_cpp.h#L1676-L1681

To fix this some approaches are as follows,

1. Replace ">=" or "<=" in the loop with a function call. Say the function will be `do_loop_comp(iter_variable, do_loop_end, increment)` which can have the following implementation,

```c
bool do_loop_comp(iter_variable, do_loop_end, increment) {
    if( increment > 0) {
        return iter_variable <= do_loop_end;
    } else {
        return iter_variable >= do_loop_end;
    }
}
```

This is not a good approach performance wise but anyways it works.

2. Do both ">=" and "<=". Yes you can replace the comparison portion in the generated loop in C backend with `((increment >= 0) && (iter_variable <= do_loop_end)) || ((increment < 0) && (iter_variable >= do_loop_end))`. There are two expressions in this, `left` (= `((increment >= 0) && (iter_variable <= do_loop_end))`) and `right` (= `((increment < 0) && (iter_variable >= do_loop_end))`). At a time only `left` or `right` will be active and not both which is what we want. This is better than the first approach. The only drawback is we are making 2 to 3 extra comparisons (depending upon whether the C compiler implements short circuiting for `&&` operation) than the usual while checking whether to exit the loop or not. 

There are several other approaches similar to 2 but they all have the overhead of some extra boolean, addition, subtraction operations.

cc: @certik

**Comment by Smit-create** [comment]
The 2nd approach is used in the LLVM backend.

**Comment by certik** [comment]
I think for compile time increments, let's create the proper increasing or decreasing loop. For runtime variables let's create the runtime if statement to dispatch. Then later our optimizer can eliminate one of the branches if it can determine that the variable is always positive or negative; if the optimizer can't do that, then we have to decide at runtime, I think there is no other way.

**Comment by czgdp1807** [comment]
> For runtime variables let's create the runtime if statement to dispatch

So you suggest to go for approach 1 (i.e., call a function which will do if else check?). I guess approach 2 is better as it doesn't call any function in each iteration.

**Comment by certik** [comment]
Either 1. or 2. is fine with me. If 2. is simpler, use 2.
