### ISSUE TITLE
C: Implementing Dictionary

### ISSUE THREAD

**Issue by Smit-create** [lcompilers/lpython#1412]
I am thinking to implement a dictionary in C, and that would follow something like this:
```c
struct dict_t1_t2 {
    T1 key;
    T2 value;
    struct dict_t1_t2 *next;
};
```

We can use this data structure further to formulate dictionary methods that we currently support in LLVM.

Let me know if this looks like a good start or if you have any suggestions.

**Comment by certik** [comment]
I think this is effectively a linked list, so very very slow. I think dictionaries in C should be implemented in exactly the same way as @czgdp1807 did in LLVM, as a hashtable.

**Comment by czgdp1807** [comment]
Yes, there are two ways,

1. Separate Chaining - What @Smit-create's suggesting.
2. Probing - What I initially implemented in LLVM, specifically linear probing.

Separate Chaining is good for key types like strings. Probing is good when we can leverage spatial locality, which is possible with types like integers. I guess both should be implemented in C. We can follow the same pattern as LLVM implementations.

**Comment by czgdp1807** [comment]
IMO, let's follow the LLVM way. First implement Probing (linear probing) and then Separate Chaining for strings.

**Comment by Smit-create** [comment]
Now since we have linear probing support for integers, we can add a fallback for other `key` types using Separate Chaining to make sure the `C` backend supports all dictionary possible types.

**Comment by nikhil061102** [comment]
If no one is working on this issue, can it be assigned to me. I am new to the world of open source contribution and is very excited to start. This will also be a good start for me for GSoC 2023
Thank You

**Comment by Smit-create** [comment]
Hi @nikhil061102, I'm working on this. Please look at some easy to fix issues so that you can get started easily.

**Comment by nikhil061102** [comment]
Ok 
No problem :)

**Comment by Smit-create** [comment]
This is fixed now.
