### ISSUE TITLE
Semantic error when defining tuple with more than 1 element

### ISSUE THREAD

**Issue by faze-geek** [lcompilers/lpython#1443]
This works for `list` but not for `tuple`. Semantic error is not generated when `tuple` contains 1 element !
```
def f():
	x:tuple[i32]
	x = (1,2,3,4,)
	print(x)

f()

(lp) C:\Users\kunni\lpython>python try.py
(1, 2, 3, 4)

(lp) C:\Users\kunni\lpython>src\bin\lpython try.py
semantic error: Type mismatch in assignment, the types must be compatible
  --> try.py:15:2
   |
15 |  x = (1,2,3,4,)
   |  ^   ^^^^^^^^^^ type mismatch ('tuple[i32]' and 'tuple[i32, i32, i32, i32]')
```

**Comment by Smit-create** [comment]
This is how `tuple` is designed in lpython where you need to specify all the types of tuple elements. Tuples are generally used to store a small number of elements. For your use case above, you can use `list[i32]` here.
```py
% cat a.py
def f():
    x: tuple[i32, i32, i32, i32]
    x = (1,2,3,4,)
    print(x)
    y: list[i32]
    y = [1,2,3,4,5,5]
    print(y)
f()
(lp) lpython % lpython a.py
(1, 2, 3, 4)
[1, 2, 3, 4, 5, 5]

```

**Comment by faze-geek** [comment]
> This is how `tuple` is designed in lpython where you need to specify all the types of tuple elements. 

Thanks! I will keep this in mind.
>Tuples are generally used to store a small number of elements. For your use case above, you can use `list[i32]` here. 

Why was this assumption considered while designing `tuple`, seems a bit strange if user is expected to keep this in mind!
An improvement that I can think of here is use of this syntax `'...'` which is allowed in python (even for multiple separated datatypes) 

```
def f():
	x:tuple[i32,...]  # Seems more suitable rather than i32 9x times.
	x = (1,2,3,4,5,6,7,8,9)
	print(x)

f()

(lp) C:\Users\kunni\lpython>python try.py
(1, 2, 3, 4, 5, 6, 7, 8, 9)

```
