### ISSUE TITLE
ASR Args are Really Parameters

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#1446]
A list of types and identifiers in the declaration of a function is a list of _formal parameters_, not arguments. The ASR nodes are mis-named. Arguments pertain only to call-nodes; more fully, they are called _actual arguments_. In declaration context, parameters are symbols without values. Arguments show up at call sites, where they are naked (recursively computed) values not bound to any symbol until ...

This confusion is understandable as Python documentation is confused, too. But the confusion is jarring to someone trying to implement closures, lexical environments, and a substitution model for function calls (arguments evaluated in the current environment, parameters (unbound identifier symbols without values) _bound_ to arguments in a fresh environment chained to the old one.

**Comment by rebcabin** [comment]
generalization of #1418 ; tagged "duplicate"

**Comment by certik** [comment]
Yes, we should rename the nodes and the associated documentation for ASR.
