### ISSUE TITLE
`Assign` node needs a `value` field

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#1467]
```c
stmt
    = ...
    | Assign(int label, identifier variable)
    | ...
```

where does the value that I'm assigning go? Shouldn't it be 

```c
stmt
    = ...
    | Assign(int label, identifier variable, expr value)
    | ...
```

?

**Comment by certik** [comment]
You want this node: https://github.com/lcompilers/lpython/blob/main/src/libasr/ASR.asdl#L164

and documentation is here:

https://docs.lfortran.org/en/asr/asr_nodes/statement_nodes/assignment/

The `assign` node is this one: https://docs.lfortran.org/en/asr/asr_nodes/statement_nodes/assign/, not what you want.
