### ISSUE TITLE
Confusion between `Assign` and `Assignment`

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#1468]
Neither one of these make sense as written

```
stmt
    = ...
    | Assign(int label, identifier variable)
    | Assignment(expr target, expr value, stmt? overloaded)
    | ...
```

`Assign` has no place for a value. `Assignment` has `expr` for a target (shouldn't it be `identifier`?). `Assignment` has no `label`, so how does one `goto` it?

**Comment by certik** [comment]
See https://github.com/lcompilers/lpython/issues/1467#issuecomment-1404234382.

Indeed, I think `Assignment` needs a `label` field. I think all the statement nodes need it.

**Comment by rebcabin** [comment]
Am I right in assuming that `expr target` should be `identifier target`?

**Comment by rebcabin** [comment]
I see the answer, here .  the "target" is sort of like a computed address.

**Comment by certik** [comment]
Target for assignment is an expr, but we should restrict it in verify(). It can definitely be a Var, it can also be ArrayIndex (say `a(3) = 5`), there are probably a few other options, but it can't be `1 + 3 = 5`.
