### ISSUE TITLE
Don't all ASR `stmt`s need `labels`?

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#1469]
I notice that `Assign` has a `label` field:

```c
stmt
    = Allocate(alloc_arg* args, expr? stat, expr? errmsg, expr? source)
    | Assign(int label, identifier variable)
    | Assignment(expr target, expr value, stmt? overloaded)
    | Associate(expr target, expr value)
    | Cycle()
    -- deallocates if allocated otherwise throws a runtime error
    | ExplicitDeallocate(symbol* vars)
    -- deallocates if allocated otherwise does nothing
    | ImplicitDeallocate(symbol* vars)
    | DoConcurrentLoop(do_loop_head head, stmt* body)
    | DoLoop(do_loop_head head, stmt* body)
    | ErrorStop(expr? code)
```

Looks like the `Assign` `stmt` can be the target of a `goto`, no? 

Why doesn't _every_ `stmt` have a `label` field?

**Comment by certik** [comment]
Ah I remember now! The label is not needed, as it is represented by the GoToTarger ASR node. In AST every statement has a label, but not in ASR. That seems like a good design?

**Comment by rebcabin** [comment]
I like the design of GoToTarget instead of a label on every line because labels are relatively uncommon in practice, say no more than 10% of the lines?

So now this issue becomes "why does Assign have a label argument?" I admit I don't know the Fortran "Assign" statement!

**Comment by certik** [comment]
Regarding `assign`, see here for documentation: https://docs.lfortran.org/en/asr/asr_nodes/statement_nodes/assign/, which should be improved. It assigns a label to a variable, so it must have the label as an argument. You can then use the variable in a goto statement. Here is an example:

https://docs.oracle.com/cd/E19957-01/805-4939/6j4m0vn7d/index.html

This is an old Fortran feature that I do not recommend to use in modern codes. Semantically at the ASR level it allows assigning labels at runtime, but the compiler knows which values are allowed at compile time, but the actual selection will be at runtime, so it is roughly equivalent to a switch statement.

**Comment by rebcabin** [comment]
Oh, yeah. I used to use "computed goto" for this ages ago (70's)

**Comment by certik** [comment]
Yes, we support computed goto as well in ASR. These features do not seem to interact badly with other features and you can mostly just ignore them. It's needed so that LFortran can become a full featured Fortran compiler, working for any (old and new) code.
