### ISSUE TITLE
Nit: "must" is better English than "has to ..." and "needs to ..."

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#1493]
Numerous places in error messages and documentation say "has to ..." and "needs to ...". The meanings are clear, but "must" is slightly more formal and less wordy in English. 

This is a low-priority "nit-pick."

**Comment by seifashraf1** [comment]
kindly review the PR [#1537](https://github.com/lcompilers/lpython/pull/1537) solving the issue

**Comment by rebcabin** [comment]
I merged the PR.
