### ISSUE TITLE
Negative constant indexes give incorrect outputs in strings

### ISSUE THREAD

**Issue by faze-geek** [lcompilers/lpython#1536]
```
def main():
    x:str 
    x = "ABC"
    l:i32
    l = -4
    print(x[l])
main()


(lp) C:\Users\kunni\lpython>src\bin\lpython try1.py
Index -3             # Added a print statement at _lfortran_str_copy
String index out of Bounds
```
But this gives an incorrect result -
```
def main():
    x:str 
    x = "ABC"
    print(x[-4])
main()

(lp) C:\Users\kunni\lpython>src\bin\lpython try1.py
Index 0             # Added a print statement at _lfortran_str_copy
C
```

**Comment by faze-geek** [comment]
This is handled here -
```
LFORTRAN_API char* _lfortran_str_copy(char* s, int32_t idx1, int32_t idx2) {

    int s_len = strlen(s);
    if(idx1 > s_len || idx1 <= (-1*s_len)){
        printf("String index out of Bounds\n");
        exit(1);
    }
```
And gets fixed with this diff -
```
-    if(idx1 > s_len || idx1 <= (-1*s_len)){
+    if(idx1 > s_len || idx1 <= 0 ){
```

**Comment by seifashraf1** [comment]
Hi, I would like to work on this issue. I tried to reproduce the issue but I didn't get what you got in the second code snippet

I put your code in expr3.py

`(lp) seif@seif:~/Documents/GSoC/lpython$ ./src/bin/lpython examples/expr3.py`
`String index out of Bounds`

**Comment by seifashraf1** [comment]
Hi, I am working on this issue. What is the incorrect answer `print(x[l])` gave you after applying the diff? 

Is it `C` or `String index out of Bounds`? I got `String index out of Bounds` after applying the diff

**Comment by faze-geek** [comment]
> Is it `C` or `String index out of Bounds`? I got `String index out of Bounds` after applying the diff

Yes it will give  `String index out of Bounds`  because `-3<=0` condition will be true.


By printing `idx1`, I can generalize that printing some constant `K` leads to `idx1 = (s_len - K +1)` while printing a variable assigned to a number` K` leads to `idx1 = K+1` . I'm not sure why they are treated differently but I'll debug it soon.

**Comment by Smit-create** [comment]
The handling of constants made more complications:
https://github.com/lcompilers/lpython/blob/7e9b364c3ca2623d1a602d7dc97fd56f18f6cc5f/src/lpython/semantics/python_ast_to_asr.cpp#L3139-L3148

Moreover, the backend function also needs to be changed as the function `lfortran_str_copy` was meant to be a string item and not perform any slicing operations for which we already have a function called `lfortran_str_slice`.

**Comment by faze-geek** [comment]
> Moreover, the backend function also needs to be changed as the function `lfortran_str_copy` was meant to be a string item and not perform any slicing operations for which we already have a function called `lfortran_str_slice`.

Thanks! I had referred `Lfortran` too and even there `lfortran_str_copy` has the same behavior. I am not well aware of Fortran but would be interested in making a contribution to the repo once #1538 is done. I'll generate equivalent Fortran code of the above examples and test them once in `Lfortran`. What do the think ?

**Comment by Smit-create** [comment]
Sure, that would be great. Please make the same changes in LFortran with some tests after #1538 is merged. Thanks!
