### ISSUE TITLE
Should `[ ]` be treated as a `ListConstant` in the ASR ?

### ISSUE THREAD

**Issue by faze-geek** [lcompilers/lpython#1555]
I am working on built-in functions and came across this.

```
def f():
    print([])
f()

(lp) C:\Users\kunni\lpython>src\bin\lpython try.py --show-asr
(TranslationUnit (SymbolTable 1 {_lpython_main_program: (Function (SymbolTable 4 {}) _lpython_main_program (FunctionType [] () Source Implementation () .false. .false. .false. .false. .false. [] [] .false.) [f] [] [(SubroutineCall 1 f () [] ())] () Public .false. .false.), f: (Function (SymbolTable 2 {}) f (FunctionType [] () Source Implementation () .false. .false. .false. .false. .false. [] [] .false.) [] [] [(Print () [] () ())] () Public .false. .false.), main_program: (Program (SymbolTable 3 {}) main_program [] [(SubroutineCall 1 _lpython_main_program () [] ())])}) [])
```
Here I guess `[]` is treated as just open-close square brackets instead of a `ListConstant`

See this -

```
def f():
    l: list[i32] = []   # treated as ListConstant here
    print(l)
f()

(lp) C:\Users\kunni\lpython>src\bin\lpython try.py --show-asr
(TranslationUnit (SymbolTable 1 {_lpython_main_program: (Function (SymbolTable 4 {}) _lpython_main_program (FunctionType [] () Source Implementation () .false. .false. .false. .false. .false. [] [] .false.) [f] [] [(SubroutineCall 1 f () [] ())] () Public .false. .false.), f: (Function (SymbolTable 2 {l: (Variable 2 l [] Local () () Default (List (Integer 4 [])) Source Public Required .false.)}) f (FunctionType [] () Source Implementation () .false. .false. .false. .false. .false. [] [] .false.) [] [] [(= (Var 2 l) (ListConstant [] (List (Integer 4 []))) ()) (Print () [(Var 2 l)] () ())] () Public .false. .false.), main_program: (Program (SymbolTable 3 {}) main_program [] [(SubroutineCall 1 _lpython_main_program () [] ())])}) [])
```
`[]` should be a ListConstant (although I'm not aware of how that can be done), because otherwise it encounters this in `Visit_List `-
```
if( ann_assign_target_type == nullptr ) {
                tmp = nullptr;
                return ;
            }
```
And then the type caught is always `nullptr` when checked in any builtin functions.

**Comment by faze-geek** [comment]
I have also noted that `""` is treated as `StringConstant ` and `()` is treated as a `TupleConstant` for example -

```
def f():
    print(())
f()

(lp) C:\Users\kunni\lpython>src\bin\lpython try.py --show-asr
(TranslationUnit (SymbolTable 1 {_lpython_main_program: (Function (SymbolTable 4 {}) _lpython_main_program (FunctionType [] () Source Implementation () .false. .false. .false. .false. .false. [] [] .false.) [f] [] [(SubroutineCall 1 f () [] ())] () Public .false. .false.), f: (Function (SymbolTable 2 {}) f (FunctionType [] () Source Implementation () .false. .false. .false. .false. .false. [] [] .false.) [] [] [(Print () [(TupleConstant [] (Tuple []))] () ())] () Public .false. .false.), main_program: (Program (SymbolTable 3 {}) main_program [] [(SubroutineCall 1 _lpython_main_program () [] ())])}) [])
```

**Comment by anutosh491** [comment]
I personally feel this might not be a good idea . Though tuples and strings would work , but for lists where every element should be of the same data type , it wouldn't make sense to return a list defined with a generic data type as lpython is strictly typed . Would raising a Semantic Error make more sense here ? otherwise users might expect that defining an empty list would work !

**Comment by faze-geek** [comment]
> I personally feel this might not be a good idea . Though tuples and strings would work , but for lists where every element should be of the same data type , it wouldn't make sense to return a list defined with a generic data type as lpython is strictly typed . 

Yes, this makes sense. The type of an empty string `""` is still `str` and the type of an empty tuple `()` is `tuple[] ` but there is no defined type for something like this `[]`. Either it should be given a type or completely banned to the users.

**Comment by rebcabin** [comment]
Actually, more technically, the type of the elements can be anything: (List
str), (list int), whatever. A more specific type, like str or int for the
elements of [] could be useful or even necessary when type-checking writing
functions that append elements to the list. Please see Chapters 5 and 11 in
"The Little Typer."

**Comment by rebcabin** [comment]
I am aware that lists in Python are heterogenous (multiple types for the element), where lists in "The Little Typer" are homogeneous. Another difference is that lists in "The Little Typer" are inductively defined

```
List<E> ::= nil<E> | [e<E>, List<E>]
```

and lists in Python are something else, probably heterogeneous vectors

```
Vec(len, elements<U>) ::= Vec(0, []<U>) | vecprepend(e, Vec(len-1, tail(elements)<U>))
```

(just sketching ... this needs work)

We still must devise a correct type for Python lists. That is real work for me. In the short run, please don't make the mistake of saying `[]` is not a List. It is a List of length 0, the unique list of length 0, and we need to work out details of writing the types of its elements so that Lists can be heterogeneous. Maybe the type of [] should be Vec(0, Object). We'll figure it out.

**Comment by rebcabin** [comment]
Here is the pertinent example from "The Little Typer." It shows that to develop a correctly typed "length" function for `List`, one must have _typed_ empty Lists. I am not sure yet how to make _generically_ typed empty Lists, but I am sure it's not too hard. More later :)

```racket
;; -----------------------------------------------
(claim step-length
       (Π ((E U))
          (→ E
             (List E)
             Nat
             Nat)))

(define step-length
  (λ (E)
    (λ (e es length-es)
      (add1 length-es))))


;; -----------------------------------------------
(claim length
       (Π ((E U))
          (→ (List E)
              Nat)))

(define length
  (λ (E)
    (λ (es)
      (rec-List es 0 (step-length E)))))


(length Nat nil)                        ; ~~> (the Nat 0)
(length Atom nil)                       ; ~~> (the Nat 0)


(length Nat (:: 42 nil))                ; ~~> (the Nat 1)
(length Atom (:: 'foo (:: 'bar nil)))   ; ~~> (the Nat 2)
```

**Comment by rebcabin** [comment]
To make `(the (List Object) nil)`, i.e., a correctly typed empty List for Python, we'll probably need sub-types (à la Barbara Liskov). "The Little Typer" does not cover those directly. More later as I learn more :)

**Comment by rebcabin** [comment]
If you wish to track my self-learning process on types, you can here:

https://github.com/rebcabin/the-little-typer

You may also wish to track the `Pie` little language that implements the interpreter for "The Little Typer:"

https://github.com/the-little-typer/pie

**Comment by anutosh491** [comment]
> According to the type theory explained in "The Little Typer," `[]` is a list constant, and the type of the elements is `U`, where U is the Universe, a type that describes all other types except U. It is a mistake to treat [] as anything OTHER than a list constant. It is the unique list constant `nil`. It is a mistake that will build-in to the compilers a serious architectural flaw that we will regret in the future.

In that case I'm not sure how we could proceed with this . @czgdp1807 or @certik could guide us better .

**Comment by rebcabin** [comment]
yes, let's bring it up to them!
