### ISSUE TITLE
opt-in run-time type checking, e.g., bounds checking

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#1556]
Lots of compilers have a Debug mode that enables many run-time features like assert and array bounds checking. We should consider likewise in LCompilers. Not an urgent thing.

**Comment by certik** [comment]
We already do that:
```python
def main():
    x: list[i32] = [1, 2, 3]
    print(x)
    print(x[2])
    print(x[3])

main()
```
Which gives:
```console
$ lpython a.py
[1, 2, 3]
3
IndexError: List index is out of range. Index range is (0, 2), but the given index is 3
```

@rebcabin is this issue fixed?

**Comment by rebcabin** [comment]
I'd say so! Thanks!
