### ISSUE TITLE
% operator gives incorrect results compared to Cpython

### ISSUE THREAD

**Issue by faze-geek** [lcompilers/lpython#1562]
Got this while testing the % operator alongside `math.mod ` in Lpython - 

```
def f():
    print((8)%3)
    print((8)%(3))
    print(-(8)%3)          #wrong
    print((8)%-3)          #wrong
    print(-(8)%-3)
    print((-8)%3)          #wrong
    print(-8%3)            #wrong
    
f()

(lp) C:\Users\kunni\lpython>python try.py
2
2
1
-1
-2
1
1

(lp) C:\Users\kunni\lpython>src\bin\lpython try.py
2
2
-2
2
-2
-2
-2
```

**Comment by faze-geek** [comment]
`LPython` gives correct results with `math.mod` but still I feel % should be corrected because of its use at some instances in the codebase.

```
import math
def f():
    print(math.mod((8),3))
    print(math.mod((8),(3)))
    print(math.mod(-(8),3))
    print(math.mod((8),-3))
    print(math.mod(-(8),-3))
    print(math.mod((-8),3))
    print(math.mod(-8,3))
    
f()

(lp) C:\Users\kunni\lpython>src\bin\lpython try.py
2
2
1
-1
-2
1
1
```

**Comment by seifashraf1** [comment]
Hello, I would like to work on this issue. Where should I find the implementation of the % operation? 

I searched and found this function in `/lpython/src/runtime/lpython_builtin.py`

`@overload`
`def _mod(a: i32, b: i32) -> i32:`
    `return a - _lpython_floordiv(a, b)*b`

I am not sure though that I am looking at the right part.

**Comment by rebcabin** [comment]
For mathematical background, please see this Wikipedia article https://en.wikipedia.org/wiki/Modulo?wprov=sfti1. The article clarifies the several ambiguities in the choice of outputs of mod when arguments are negative. It might explain some of the answers above.

**Comment by seifashraf1** [comment]
Thank you! While this Wikipedia article will help me figure out the logic behind the right answers, I am still concerned about which parts of the codebase I should tackle to address the issue.

**Comment by Smit-create** [comment]
Just replace this:
https://github.com/lcompilers/lpython/blob/cc02ba9fd21c3fa04c6b342400280c9412651429/src/runtime/lpython_builtin.py#L525-L539

with this:
https://github.com/lcompilers/lpython/blob/cc02ba9fd21c3fa04c6b342400280c9412651429/src/runtime/math.py#L469-L473

Please modify it according to the types.

**Comment by seifashraf1** [comment]
Yeah, that is the part that I thought of modifying. Thank you! Will do that now.

**Comment by seifashraf1** [comment]
I replaced the _lpython_floordiv with another floor function identical to the ones in:

https://github.com/lcompilers/lpython/blob/cc02ba9fd21c3fa04c6b342400280c9412651429/src/runtime/math.py#L469-L473

But I still get the same incorrect results. I have been trying to investigate other potential parts and do some debugging but no luck. Any idea on what may be the problem?  

You can check my commit here: 

https://github.com/seifashraf1/lpython/commit/5355324b39d3425b473994703d2a6a666983438e

**Comment by seifashraf1** [comment]
Update: I tried to edit the _mod function to this trying to see how it will affect the output of f() as I was a little suspicious that the output of f() is not affected by my changes in _mod. 

```
def _mod(a: i32, b: i32) -> i32:         
    """
    Returns a%b  
    """
    return 0

(lp) seif@seif:~/Documents/GSoC/lpython$ ./src/bin/lpython examples/try.py
2
2
-2
2
-2
-2
-2

``` 

This is weird as I expected all the results to be 0. I think the reason behind this is what is making my changes in the commit mentioned in the above comment have no effect on the results. I made sure to run ./build0.sh and ./build1.sh of course before testing try.py.

**Comment by gptsarthak** [comment]
Hi! I'm also new to contributing here, this is what I understood:
LPython right now evaluates the modulo function during compile time. 
https://github.com/lcompilers/lpython/blob/3c53ffb1c217405224ff53f0b3a7a5d306fb07d7/src/lpython/semantics/python_comptime_eval.h#L211-L216
Here we are simply returning the value of a%b in C code.
However, behavior of modulo function is different in C and Python.
If we change ```a%b``` to ```((a%b)+b)%b``` we get the correct output for all cases mentioned. I have tried and tested this locally.
Reference - https://stackoverflow.com/questions/1907565/c-and-python-different-behaviour-of-the-modulo-operation

Is this the correct solution to the issue, or maybe a temporary fix? Or is the modulo function actually supposed to be evaluated at runtime instead?

**Comment by seifashraf1** [comment]
wow, I did not know that. I got the correct results too after that change. I think that was my problem because when I tried to check the C code generated by doing `--show-cpp` and compiling it separately it got me the correct results too. So I think this is probably the correct solution to the issue.

**Comment by seifashraf1** [comment]
Should I create a PR with my changes and then you can commit this change in a separate PR or how do you wanna do it? @gptsarthak

**Comment by faze-geek** [comment]
Thanks @gptsarthak for the sleuthing. I have fixed it along with some edge cases of compile time evaluation in my pr. 
Note that modulo by `0` edge case is not fixed for runtime evaluations like here -

```
def f():
    a:i32 = 8
    b:i32 = 0
    print(a%b)

f()
(lp) faze-geek@DESKTOP-497JDCU:~/lpython/lpython$ python try.py
Traceback (most recent call last):
  File "/home/faze-geek/lpython/lpython/try.py", line 6, in <module>
    f()
  File "/home/faze-geek/lpython/lpython/try.py", line 4, in f
    print(a%b)
          ~^~
ZeroDivisionError: integer modulo by zero
(lp) faze-geek@DESKTOP-497JDCU:~/lpython/lpython$ ./src/bin/lpython try.py
8
```
This will be fixed in the `_mod()` function of `lpython_builtin.py` which I beleive @seifashraf1 was looking into. Thanks !
