### ISSUE TITLE
Tuples without `( )` should be identified

### ISSUE THREAD

**Issue by faze-geek** [lcompilers/lpython#1577]
Came across this while trying out a minimal case for #1210 
```

def f():
    t: tuple[i32,i32] = 2,3                              # Here (2, 3) will give expected output
    print(t)

f()

(lp) C:\Users\kunni\lpython>python try.py
(2, 3)

(lp) C:\Users\kunni\lpython>src\bin\lpython try.py
syntax error: Token ',' is unexpected here
  --> try.py:19:25
   |
19 |     t:tuple[i32,i32] = 2,3
   |                         ^

```

**Comment by harshsingh-24** [comment]
Okay. I will try to work on this issue. Thanks for confirming @faze-geek

**Comment by harshsingh-24** [comment]
Okay. So I understood a few things, which I would like to jot down - 

- If we are following the approach of normal Python, then a statement like `t=2,` (where comma is present after 2) implies that t is a tuple whereas `t=2` implies that t is an integer.
- LPython as of now supports the above implementations with brackets, that is, `t : tuple[i32] = (2,)` is the minimal valid tuple in LPython. `t: tuple[i32] = (2)` [without comma after 2], is still considered semantically incorrect as `(2)` is an integer in Python.

Lpython needs to support without bracket tuple formation approach, as of now, in this fix. Do we also need to support base cases like `t: tuple[i32] = 2` [without commas after a single entity] in this fix,?

**Comment by Thirumalai-Shaktivel** [comment]
I think, we already support tuples without brackets and this issue is some corner case that we missed.
@harshsingh-24 this issue is related to the `parser`, so you can fix this in the `parser.yy`.

**Comment by harshsingh-24** [comment]
@Thirumalai-Shaktivel You were right that the support of tuples without brackets is already present. 

LPython is able to do `tuple-unpacking` for the following test case - 

**Case 1: (Working)**

```
def f():
    t : tuple[i32, i32]
    t = 2,3                         # Tuple unpacking is supported. Works with and without brackets 
    print(t)

f()
```

But LPython is unable to do `tuple-unpacking` for the following test case - 

**Case 2: (Not-Working)**
```
def f():
    t : tuple[i32, i32] = 2,3                         # This does not work without brackets
    print(t)

f()
``` 

The reason which I found is that `Case 1` makes use of `assignment_statement` (Non-terminal) which further calls `tuple_list` (a non-terminal responsible for tuple unpacking with and without brackets) as shown below: 

```
assignment_statement
     : target_list tuple_list { $$ = ASSIGNMENT($1, $2, @$); }
     | target_list yield_expr { $$ = ASSIGNMENT($1, $2, @$); }
     | target_list tuple_list TK_TYPE_COMMENT {$$ = ASSIGNMENT2($1, $2, $3, @$); }
     ;

 tuple_list
     : expr { $$ = $1; }
     | expr_list "," expr { $$ = TUPLE_01(TUPLE_($1, $3), @$); }
     | expr_list "," { $$ = TUPLE_03($1, @$); }
     ;

```

Whereas `Case 2` makes use of `ann_assignment_statement` which calls `expr` non-terminal, which supports tuples only with brackets, as shown below - 

```
 ann_assignment_statement
     : expr ":" expr { $$ = ANNASSIGN_01($1, $3, @$); }
     | expr ":" expr "=" expr { $$ = ANNASSIGN_02($1, $3, $5, @$); }
     ;

expr: 
       "(" ")"                                     { $$ = TUPLE_EMPTY(@$); }
     | "(" expr_list "," ")"                       { $$ = TUPLE_03($2, @$); }
     | "(" TK_TYPE_IGNORE expr_list "," ")"        { $$ = TUPLE_03($3, @$); extract_type_comment(p, @$, $2); }
     | "(" expr_list "," expr ")"                  { $$ = TUPLE_01(TUPLE_($2, $4), @$); }
     | "(" TK_TYPE_IGNORE expr_list "," expr ")"   { $$ = TUPLE_01(TUPLE_($3, $5), @$); extract_type_comment(p, @$, $2);}
```

I think, I need to modify the grammar associated with `expr` non-terminal symbol and make it support without brackets as well. Can you please confirm? @Thirumalai-Shaktivel @Smit-create @faze-geek

**Comment by Thirumalai-Shaktivel** [comment]
Exactly! Just replace `expr` to `tuple_list`. I  think that should work.
```
 ann_assignment_statement
     : expr ":" expr { $$ = ANNASSIGN_01($1, $3, @$); }
     | expr ":" expr "=" tuple_list { $$ = ANNASSIGN_02($1, $3, $5, @$); }
     ;
```

**Comment by harshsingh-24** [comment]
Incorporating the above changes and doing a build, now I don't see the bug appearing. Do I need to do anything else before pushing the code?

**Comment by Thirumalai-Shaktivel** [comment]
You can add `t: tuple[i32,i32] = 2,3` to `tests/parser/tuple1.py` and update tests using `./run_tests.py -u` and submit a PR for it.

**Comment by harshsingh-24** [comment]
@Thirumalai-Shaktivel My CI pipeline is failing for the Linux and MacOs system. Can you please help me out? I think the hashes are not matching.
