### ISSUE TITLE
ASR: add UnsignedInteger

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#1588]
The UnsignedInteger, just like the default (signed) Integer should be checked in Debug and ReleaseSafe mode for overflow (from both sides). In Release mode they are not checked for performance.

We have to carefully check that this design fixes all the pitfalls at https://github.com/lcompilers/lpython/wiki/ASR-Design#unsigned-integers, but it looks like it might.

If wraparound is required, then the design at #1578 should be used.

Implementation:

* [x] Initial implementation: https://github.com/lcompilers/lpython/pull/1764
* [x] Add tests for all corner cases, harden the implementation
  * [x] https://github.com/lcompilers/lpython/pull/1769
  * [x] https://github.com/lcompilers/lpython/pull/1770
  * [x] https://github.com/lcompilers/lpython/pull/1775
* [x] Debug time wraparound check -> implement later: https://github.com/lcompilers/lpython/issues/1776

**Comment by certik** [comment]
For example, for `unsigned int a = 1000; signed int b = -1; (a > b)`, in LPython it would look like:
```python
a: u16 = 1000
b: i16 = -1
a > u16(b)
```
We must decide how `u16(b)` where `b` is signed should be handled. It can either cast negative integers to positive (no bit changes), or it can give an error message.

**Comment by rebcabin** [comment]
I believe C just re-uses the bit pattern: https://replit.com/join/jlxoloezhd-brianbeckman

**Comment by certik** [comment]
Yes, C does. Rust, on the other hand, does not allow you to do this:
```rust
    let a: u8 = 100;
    let b: i8 = -1;
    let val: bool = a > b;                    
```
which gives:
```console
$ cargo run     
   Compiling xx v0.1.0 (/private/tmp/xx)
error[E0308]: mismatched types
 --> src/main.rs:5:25
  |
5 |     let val: bool = a > b;
  |                         ^ expected `u8`, found `i8`
  |
help: you can convert an `i8` to a `u8` and panic if the converted value doesn't fit
  |
5 |     let val: bool = a > b.try_into().unwrap();
  |                          ++++++++++++++++++++

For more information about this error, try `rustc --explain E0308`.
error: could not compile `xx` due to previous error
```
and this:
```rust
    let a: u8 = 100;
    let b: i8 = -1;
    let val: bool = a > b.try_into().unwrap();
```
gives:
```console
$ cargo run     
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/xx`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TryFromIntError(())', src/main.rs:5:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So the default way that the rust compiler recommended to convert i8 to u8 is the "safe" method, which gives a runtime error if it does not fit exactly.

**Comment by Smit-create** [comment]
So, do we want to introduce a new type in ASR like `UnsignedInteger`?

**Comment by czgdp1807** [comment]
> If we are going to support unsigned integers, one clean way to do it is to introduce an opaque type, such a OpaqueType(identifier name, int size_in_bytes), where the frontend can set u8, u16, etc. for name, and the number of bytes it occupies in memory.

Suggested in https://github.com/lcompilers/lpython/wiki/ASR-Design#unsigned-integers

https://github.com/lcompilers/lpython/issues/1578 is also one way. 

However I think `UnsignedInteger` is the cleanest for now. You can go ahead with it. If @certik says to use one of the other two designs then we can always update.

**Comment by certik** [comment]
This is now implemented, see the issue description for the 4 PRs that implemented it. There might still be bugs, but if there are, we'll fix it as they are reported.
