### ISSUE TITLE
Implement ConstantTuple visitor in LLVM

### ISSUE THREAD

**Issue by namannimmo10** [lcompilers/lpython#162]
They are needed in the implementation of runtime built-in functions, like `divmod()` where we return a pair.

**Comment by Thirumalai-Shaktivel** [comment]
I think this issue is fixed:
https://github.com/lcompilers/lpython/blob/8ba6a318b6d7e58b1dd9829eaf1c787a92fec396/integration_tests/test_builtin_divmod.py#L1-L13

**Comment by Smit-create** [comment]
Yeah, that's right!
