### ISSUE TITLE
Bug: "x : i32 = test()" fails at top level

### ISSUE THREAD

**Issue by gptsarthak** [lcompilers/lpython#1667]
Running
```Python
def test() -> i32:
    temp: i32 = 0
    return temp

x : i32 = test()
# print(x)  Will give segmentation fault
```
gives  ``` code generation error: Function code not generated for 'test' ``` .

But declaring and assigning in different line
```
x : i32
x = test()
print(x)
```
compiles successfully.
Not sure if this is intentional. This type of code runs fine in CPython.

**Comment by certik** [comment]
That's a bug, in fact two separate bugs, one a segfault, the other one "code generation error: Function code not generated for 'test'", both need to be investigated and fixed. Given how simple the code is, I think this is a high priority bug, so I put it into our roadmap: https://github.com/lcompilers/lpython/issues/1600.

**Comment by Thirumalai-Shaktivel** [comment]
I can see two different issues, here:
1. 
```py
def test() -> i32:
    temp: i32 = 0
    return temp

x : i32 = test()
```
The above code doesn't have any statements, so function-call to `_lpython_main_program` is not happening
2.
```py
def test() -> i32:
    temp: i32 = 0
    return temp

x : i32 = test()
print(x)
```
Here x is a `global_variable` and we are initializing it using a function call. I think that is the reason for the seg_fault.
