### ISSUE TITLE
String length issue in LLVM

### ISSUE THREAD

**Issue by namannimmo10** [lcompilers/lpython#175]
```python
def test_len():
    s: str
    s = "abcd"
    assert len(s) == 4
    s = ''
    assert len(s) == 0
    assert len("abcd") == 4
    assert len("") == 0
```
⬆️  When we run this under integration tests, it returns a codegen error, as it hits this line 👇 
 https://github.com/lcompilers/lpython/blob/e1b2778dc30d413a6ce3abb698ff52c1598240f9/src/libasr/codegen/asr_to_llvm.cpp#L1518

**Comment by certik** [comment]
I am reopening this, as it doesn't work yet in main, but I have a fix for this in my local branch.
