### ISSUE TITLE
Issue with global scope

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#1786]
```python
import sys
if False:
    sys.exit(1)
```
gives
```console
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
LCompilersException: visit_If() not implemented
```
This might already be fixed in master, let's check.

**Comment by Shaikh-Ubaid** [comment]
It seems we currently support calling `exit` by using:
```python
from sym import exit

exit(1)
```
Using `sys.exit(1)` results in looking up of `exit` in `AttributeHandler` and consequent failure.
