### ISSUE TITLE
Usability issues

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#1802]
These are relatively simple usability issues that we should fix. High priority (blocker):

* [x] https://github.com/lcompilers/lpython/issues/1890
* [x] #1799 
* [ ] #1787 
* [x] #1798 - https://github.com/lcompilers/lpython/pull/1822
* [ ] #1801 
* [x] https://github.com/lcompilers/lpython/issues/1915
* [x] https://github.com/lcompilers/lpython/issues/1914

Medium priority:

* [x] https://github.com/lcompilers/lpython/issues/1859
* [x] https://github.com/lcompilers/lpython/issues/1867

Lower priority:

* [x] https://github.com/lcompilers/lpython/issues/1896
* [x] https://github.com/lcompilers/lpython/issues/1893
* [x] #1781 - https://github.com/lcompilers/lpython/pull/1805
* [x] #1784 
* [x] #1785 (https://github.com/lcompilers/lpython/pull/1829, https://github.com/lcompilers/lpython/pull/1815)
* [x] #1788 
* [x] #1789 
* [x] #1790 
* [x] #1793 
* [x] #1797
* [x] #1800 
* [ ] https://github.com/lcompilers/lpython/issues/1809
* [x] https://github.com/lcompilers/lpython/issues/1818
* [ ] https://github.com/lcompilers/lpython/issues/1817
* [ ] https://github.com/lcompilers/lpython/issues/1819
* [x] https://github.com/lcompilers/lpython/issues/1849

**Comment by Shaikh-Ubaid** [comment]
Most of the issues here seem fixed. Closing in favour of https://github.com/lcompilers/lpython/issues/2345.
