### ISSUE TITLE
Test lpython.py with multiple CPython versions

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#1827]
We need to test the lpython.py tests in integration_tests with multiple CPython versions. It looks like there are some bugs related to that.

**Comment by rebcabin** [comment]
How about just picking CPython 3.11 and committing to it to reduce our
workload until LPython is 99% feature-complete?

**Comment by Shaikh-Ubaid** [comment]
We currently test with `Python 3.10` and `Python 3.11.4` at the CI. Is this issue safe to close or shall we test other Python versions like `Python 3.9`, `Python 3.8` at the CI?

**Comment by certik** [comment]
We should test with all the Python versions at: https://www.python.org/downloads/, so let's test with 3.8, 3.10, 3.11 and 3.12. To save time, we can probably skip 3.9. Once 3.8 is deprecated, we can test 3.9 instead.

**Comment by Shaikh-Ubaid** [comment]
It seems `list` type is not subscriptable in Python `3.8`.

```
$ python --version
Python 3.8.17
```
```
$ cat examples/expr2.py 
from lpython import i32

def print_list(a: list[i32]):
    print(a)

def main0():
    x: list[i32] = [1, 2, 3]
    print_list(x)

main0()
```
```
$ python examples/expr2.py
Traceback (most recent call last):
  File "examples/expr2.py", line 3, in <module>
    def print_list(a: list[i32]):
TypeError: 'type' object is not subscriptable
```
```
$ lpython examples/expr2.py 
[1, 2, 3]
```

Please, could you share what we should do?

**Comment by Shaikh-Ubaid** [comment]
It seems annotation for `list` is supported since `Python 3.9` (reference https://stackoverflow.com/a/64755075).

**Comment by certik** [comment]
Ok, then Let's test Python 3.9, 3.10 and 3.11 explicitly, all three. Once 3.12 is released in October, we'll add it as well.

**Comment by Shaikh-Ubaid** [comment]
For Python 3.8 and before, it seems one needs to use `from typing import List` (which I think is subscriptable).

**Comment by Shaikh-Ubaid** [comment]
>Ok, then let's test Python 3.9, 3.10 and 3.11 explicitly, all three. Once 3.12 is released in October, we'll add it as well.

Sure, got it.
