### ISSUE TITLE
Support List Compare like String Compare (index by index)

### ISSUE THREAD

**Issue by faze-geek** [lcompilers/lpython#1832]
```
print([3,4,5]<[1,6,7])             # Expected output is false

semantic error: Compare: only Integer, Real, Logical, or String can be on the LHS and RHS.If operator is Eq or NotEq then Complex type is also acceptable
 --> try.py:2:11
  |
2 |     print([3,4,5]<[1,6,7])
```

**Comment by AtmegaBuzz** [comment]
@faze-geek Are you working on this ? if not then i would like to take this issue

**Comment by faze-geek** [comment]
> @faze-geek Are you working on this ? if not then i would like to take this issue
> 

No, you can go ahead and attempt it @AtmegaBuzz

**Comment by AtmegaBuzz** [comment]
Thank you 😊

**Comment by AtmegaBuzz** [comment]
@faze-geek I ran this in cpython and this is what i get. I am little confuse what is the logic behind the comparison 
![image](https://github.com/lcompilers/lpython/assets/68425016/300a7832-2e78-489d-aa80-88d02cd79a7b)
print([1,1,10,10,6]>[1,6,7,1,1]) should be true but its giving false
