### ISSUE TITLE
Bad error message for `Optional[list[str] | str]`

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#1953]
repro: 

```python
# from typing import Optional # uncomment for CPython; comment for LPython

NEWLINE      : str       = "\n"
WHITESPACE   : list[str] = [" ", ",", NEWLINE, "\r", "\t"]


def match(pat : str, string : str) -> Optional[list[str] | str]:
    return None
```

produces:

```bash
└─(06:39:53 on brian-lasr ✹ ✭)──> ~/CLionProjects/lpython/src/bin/lpython -I. lasr_lexer_optional_list.py                                             2 ↵ ──(Mon,Jun19)─┘
semantic error: Variable 'list' not declared
 --> lasr_lexer_optional_list.py:7:48
  |
7 | def match(pat : str, string : str) -> Optional[list[str] | str]:
  |                                                ^^^^ 
```

**Comment by aryangupta701** [comment]
Hi can you please assign this issue to me?

**Comment by Shaikh-Ubaid** [comment]
As per the latest main, the example in the issue description produces.
```console
% cat examples/expr2.py 
NEWLINE      : str       = "\n"
WHITESPACE   : list[str] = [" ", ",", NEWLINE, "\r", "\t"]


def match(pat : str, string : str) -> Optional[list[str] | str]:
    return None
% lpython examples/expr2.py
semantic error: The type 'Optional' is undeclared.
 --> examples/expr2.py:5:39
  |
5 | def match(pat : str, string : str) -> Optional[list[str] | str]:
  |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lcompilers/lpython/issues.
```
which is as expected.

**Comment by Shaikh-Ubaid** [comment]
Let's add an error reference test for this and then close this issue.

**Comment by Shaikh-Ubaid** [comment]
>Hi can you please assign this issue to me?

I assigned it to you. We need to add an error reference test. https://github.com/lcompilers/lpython/commit/5002fbf948d48e9da10729cb09701a45038625af is a good example of adding an error reference test. If you have any doubts, please ask.

**Comment by aryangupta701** [comment]
okay so you mean that now the error message is correct and we need to just add a test for it to close it.

**Comment by Shaikh-Ubaid** [comment]
> okay so you mean that now the error message is correct and we need to just add a test for it to close it.

Yes.

**Comment by aryangupta701** [comment]
Thank you. Really loved the quick responses in this community. I will ask if I am stuck anywhere.

**Comment by aryangupta701** [comment]
[[test]]
filename = "errors/test_str_slicing3.py"
asr = true

what is the meaning of asr?

**Comment by aryangupta701** [comment]
Also I didn't understand how is this hash given to a file name 
for eg: asr-test_str_to_int-61553e7.stderr has a hash `61553e7` didn't really understand where it came from

**Comment by Shaikh-Ubaid** [comment]
ASR is Abstract semantic representation. It is also known as a semantic tree in compilers. Like other compilers, LPython first converts the source code to tokens which are then converted to AST. The AST is then converted to ASR. ASR is passed through several ASR->ASR passes and then converted to the output via the desired backend.

You can see https://docs.lfortran.org/en/ for a basic idea of things.

**Comment by Shaikh-Ubaid** [comment]
>Also I didn't understand how is this hash given to a file name

It is auto-generated. Once you add your changes as shown in the above shared commit, you just need to update the reference tests. 

To update the reference tests we need to do:
```console
./run_tests.py -u
```

**Comment by aryangupta701** [comment]
okay got it thank you

**Comment by aryangupta701** [comment]
```
 lpython git:(error-ref) ✗ ./run_tests.py -u
  File "./run_tests.py", line 44
    raise Exception(f"Unknown pass: {pass_}")
    ```
    
I think I am not able to find any good documentation to set up my project. I went to contributing.md file and it didn't had much information about setting up locally. Can you please provide a documentation for that to help me solve the above error?

**Comment by Shaikh-Ubaid** [comment]
You can follow the setup instructions in the `README.md` at https://github.com/lcompilers/lpython.

**Comment by Shaikh-Ubaid** [comment]
By the way, what operating system do you use?

**Comment by aryangupta701** [comment]
I use ubuntu 20.04
