### ISSUE TITLE
String comparison

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#197]
Currently string comparison such as `assert x = "abc"` doesn't work properly yet, I think we should implement the operation in LPython in the runtime library and the frontend should insert the call to it.

**Comment by certik** [comment]
Here is how to do it:
```python
def _lpython_str_equal(a: str, b: str) -> bool:
    if len(a) != len(b):
        return False
    i: i32
    for i in range(len(a)):
        if a[i] != b[i]:
            return False
    return True

def f():
    assert _lpython_str_equal("a", "a")
    assert not _lpython_str_equal("a2", "a")
    assert not _lpython_str_equal("a", "a123")
    assert not _lpython_str_equal("a23", "a24")
    assert _lpython_str_equal("a24", "a24")
    assert _lpython_str_equal("abcdefg", "abcdefg")
    assert not _lpython_str_equal("abcdef3", "abcdefg")

f()
```
Currently fails in the LLVM backend.

**Comment by certik** [comment]
With #198 the above snippet now works.

**Comment by namannimmo10** [comment]
I tried the following:
```python
def main0():
  s1: str
  s1 = "abc"
  s2: str
  s2 = "ab"
  assert s1 == s2

main0()
```
And it worked. So it seems like it is only comparing the first character of the strings,

https://github.com/lcompilers/lpython/blob/1d7ba2e6de540c7a5a926fe70ae3a32c88adcfd0/src/libasr/codegen/asr_to_llvm.cpp#L2630-L2641

**Comment by certik** [comment]
Yes, we have to fix it, I think the best way is for the front end to implement `s1 == s2` by inserting `lpython_str_compare(s1, s2)`. It can be implemented in LPython itself. This is one of those functions that are "intrinsic" and the LLVM backend can choose to implement it differently if there is some more efficient implementation depending on the string implementation in the backend. See https://github.com/lcompilers/lpython/wiki/Intrinsic-Functions-Design for more info.
