### ISSUE TITLE
Improve error message for undefined user type

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#1993]
This:
```python
def check_re_range_alternatives(
        alts : list[ReRange],
        char : str) -> bool:
    result : bool = False
    rr : ReRange
    for rr in alts:
        if check_re_range(rr, char):
            result = True
            break
    return result
```
gives:
```console
$ lpython a.py 
semantic error: Unsupported type annotation: ReRange
 --> a.py:2:21
  |
2 |         alts : list[ReRange],
  |                     ^^^^^^^ 
```
But rather the error message should be:
```
semantic error: The type `ReRange` is not declared
```
or
```
semantic error: Unknown type `ReRange`
```
I think I like the second more.

Regarding "Unsupported type annotation: ReRange", that should be emitted for things like `from typing import List`. If you just do `List[i32]` without importing it from anywhere, then I think it should just say `Unknown type List`, and we can provide a "hint: did you mean `list`?"

**Comment by Shaikh-Ubaid** [comment]
With respect to this issue, shall we update the error message as follows:
```bash
diff --git a/src/lpython/semantics/python_ast_to_asr.cpp b/src/lpython/semantics/python_ast_to_asr.cpp
index b5b4ed779..401eb8b4c 100644
--- a/src/lpython/semantics/python_ast_to_asr.cpp
+++ b/src/lpython/semantics/python_ast_to_asr.cpp
@@ -1092,7 +1092,7 @@ public:
         }
 
         if( !type && raise_error ) {
-            throw SemanticError("Unsupported type annotation: " + var_annotation, loc);
+            throw SemanticError("Unknown type `" + var_annotation + "`", loc);
         }
 
         return type;
(END)
```

Some examples of how it would look:
```bash
(lp) ubaid@ubaids-MacBook-Pro lpython % cat examples/expr2.py    
def main0():
    x: ReRange

main0()
(lp) ubaid@ubaids-MacBook-Pro lpython % lpython examples/expr2.py
semantic error: Unknown type `ReRange`
 --> examples/expr2.py:2:8
  |
2 |     x: ReRange
  |        ^^^^^^^ 


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that must be fixed).
(lp) ubaid@ubaids-MacBook-Pro lpython % cat examples/expr2.py    
def main0():
    x: ReRange[i32]

main0()
(lp) ubaid@ubaids-MacBook-Pro lpython % lpython examples/expr2.py
semantic error: Unknown type `ReRange`
 --> examples/expr2.py:2:8
  |
2 |     x: ReRange[i32]
  |        ^^^^^^^^^^^^ 


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that must be fixed).
(lp) ubaid@ubaids-MacBook-Pro lpython % cat examples/expr2.py    
def main0():
    x: list[ReRange]

main0()
(lp) ubaid@ubaids-MacBook-Pro lpython % lpython examples/expr2.py
semantic error: Unknown type `ReRange`
 --> examples/expr2.py:2:13
  |
2 |     x: list[ReRange]
  |             ^^^^^^^ 


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that must be fixed).
(lp) ubaid@ubaids-MacBook-Pro lpython % cat examples/expr2.py    
def main0():
    x: List[ReRange]

main0()
(lp) ubaid@ubaids-MacBook-Pro lpython % lpython examples/expr2.py
semantic error: Unknown type `List`
 --> examples/expr2.py:2:8
  |
2 |     x: List[ReRange]
  |        ^^^^^^^^^^^^^ 


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that must be fixed).
```

**Comment by Shaikh-Ubaid** [comment]
>If you just do List[i32] without importing it from anywhere, then I think it should just say Unknown type List, and we can provide a "hint: did you mean list?"

Is this a part of this issue? It seems there could several similar hints, for example `Unknown type I32`, `hint: Use i32` and similarly for other types.

**Comment by certik** [comment]
Yes, we can do hints in some other issue.

@rebcabin what exact error message text would you recommend here?

**Comment by tanay-man** [comment]
@certik Is this error message acceptable?
![image](https://github.com/lcompilers/lpython/assets/93091118/67cacf7c-f841-4b97-93cc-0d942b7dbf5c)

**Comment by rebcabin** [comment]
I like "semantic error: The type 'ReRange' is undeclared."

Note the punctuation: ReRange must appear in quotes and the entire message must end with a period because the message is a sentence with a subject, object, and verb. An error message like "Unknown type: ReRange" is also acceptable. In such an error message, ReRange is NOT in quotes and the message is not terminated with a period because the message is NOT a sentence, it's just a noun phrase. See any edition of "The Gregg Reference Manual" for the rules of English punctuation. It's important for our messages to be grammatical and correctly punctuated. Otherwise, fluent English readers will be distracted by the errors and they will also get an impression that our outputs are less than professional.

**Comment by tanay-man** [comment]
I agree, grammatically incorrect error messages are distracting. I will change it to "semantic error: The type 'ReRange' is undeclared." I dont know if this is the correct place to ask this but after changing the thrown error, do the tests need to be updated?

**Comment by rebcabin** [comment]
Yes, all the tests must pass before submitting a pull request :) We have continuous integration, too, which probably checks this.

```
ctest
./run_tests.py
pushd integration_tests
./run_tests.py
popd
```

**Comment by aryangupta701** [comment]
is this solved?

**Comment by Shaikh-Ubaid** [comment]
With the latest main, the example in the issue description now gives:
```console
% cat examples/expr2.py 
def check_re_range_alternatives(
        alts : list[ReRange],
        char : str) -> bool:
    result : bool = False
    rr : ReRange
    for rr in alts:
        if check_re_range(rr, char):
            result = True
            break
    return result
% lpython examples/expr2.py 
semantic error: The type 'ReRange' is undeclared.
 --> examples/expr2.py:2:21
  |
2 |         alts : list[ReRange],
  |                     ^^^^^^^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lcompilers/lpython/issues.
```

**Comment by Shaikh-Ubaid** [comment]
I think this issue is fixed with the latest main.
