### ISSUE TITLE
Cpython Bug: c_p_pointer 

### ISSUE THREAD

**Issue by ronnuriel** [lcompilers/lpython#2095]
This code used to work on previous Lpython version, 
seems like `c_p_pointer` implementation changed.. 
and crashes in `ctypes.cast(cptr, ctypes.py_object).value`

Example code:
```
from lpython import i32, f64, i64, dataclass, ccall, union, Union, packed, u32, u16, u64, CPtr, sizeof, c_p_pointer, Pointer
import numpy as np
import ctypes

@packed
@dataclass
class cht_gchl_init_once_st:
    test_indx: u32



def gdl_mem_alloc_nonull_wrapper(buf_size: i64) -> i64:
    xs = np.empty(buf_size, dtype=np.uint8)
    p = ctypes.c_void_p(xs.ctypes.data)
    return p.value


def gdl_mem_handle_to_host_ptr(handle: i64) -> CPtr:
    new_ptr = ctypes.cast(handle, ctypes.c_void_p)
    return new_ptr


gchl_init_once_hndl = gdl_mem_alloc_nonull_wrapper(sizeof(cht_gchl_init_once_st))

gchl_init_once_cmd: CPtr = gdl_mem_handle_to_host_ptr(gchl_init_once_hndl)

p_gchl_init_once_cmd: Pointer[cht_gchl_init_once_st] = c_p_pointer(gchl_init_once_cmd, cht_gchl_init_once_st)

p_gchl_init_once_cmd.test_indx = u32(13)
```

Error massage:
`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`

Lpython version that works:
```
LPython version: 0.15.0
Platform: macOS ARM
Default target: arm64-apple-darwin22.5.0

```

**Comment by certik** [comment]
I get the following error message:
```
$ lpython c.py
semantic error: Could not find the module 'ctypes'. If an import path is available, please use the `-I` option to specify it
 --> c.py:3:1
  |
3 | import ctypes
  | ^^^^^^^^^^^^^ 
```
You can't use ctypes with LPython.

**Comment by ronnuriel** [comment]
> I get the following error message:
> 
> ```
> $ lpython c.py
> semantic error: Could not find the module 'ctypes'. If an import path is available, please use the `-I` option to specify it
>  --> c.py:3:1
>   |
> 3 | import ctypes
>   | ^^^^^^^^^^^^^ 
> ```
> 
> You can't use ctypes with LPython.

Talking about Cpython using lpython.py

**Comment by certik** [comment]
Look into `integration_tests/bindc_07.py` how to use this:
```
def sum_arrays(array1: CPtr, array2: CPtr, array3: CPtr, array4: CPtr, \
        array5: CPtr, array6: CPtr, array7: CPtr, array8: CPtr, size: i32):
    iarray1: Pointer[i8[:]] = c_p_pointer(array1, i8[:], array([size]))
    iarray2: Pointer[i16[:]] = c_p_pointer(array2, i16[:], array([size]))
    iarray3: Pointer[i32[:]] = c_p_pointer(array3, i32[:], array([size]))
```

**Comment by ronnuriel** [comment]
> Look into `integration_tests/bindc_07.py` how to use this:
> 
> ```
> def sum_arrays(array1: CPtr, array2: CPtr, array3: CPtr, array4: CPtr, \
>         array5: CPtr, array6: CPtr, array7: CPtr, array8: CPtr, size: i32):
>     iarray1: Pointer[i8[:]] = c_p_pointer(array1, i8[:], array([size]))
>     iarray2: Pointer[i16[:]] = c_p_pointer(array2, i16[:], array([size]))
>     iarray3: Pointer[i32[:]] = c_p_pointer(array3, i32[:], array([size]))
> ```

Can it be fixed working also with the previous version? 
We have a lot of code that followed the prev conventions..

**Comment by certik** [comment]
In terms of effort, it is probably more effort to support both ways in the compiler than to update your code --- we'll help you, it will go quick. I am sorry that we broke this --- we try not to do that in general, but in this case the old version didn't work properly with the type system (I forgot the details).
