### ISSUE TITLE
In emulation mode, u8-u64 should be represented by just int

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#2173]
Currently we created our own class UnsignedInteger and we provide a CPython incompatible behavior of some operators such as ~. Rather, if we need a CPython incompatible behavior, we should introduce some special functions, such as `from lpython import uneg`. The intrinsic operators should work just like in CPython.

Here is an example:
```python
print(u16(0xff), 0xff)
print(~u16(0xff), ~0xff)
```
This currently prints:
```
255 255
65280 -256
```
So the `~` is behaving differently for u16 and Python ints. It should not. The design of u16 and i16 is that they are strict value restricted subset of Python ints and should behave exactly identical on this subset, and LPython should give compile time or runtime error messages if any operation is performed outside of this subset. 

Since in CPython ~255 becomes -256, then the same behavior must happen on ~u16(255). In order to provide the other operation, we can make `uneg(255)` be 65280. Then the operation can be correctly implemented in emulation mode, and all unsigned integers can be just integers, which will speedup operation and remove many bugs that we currently have, when we are passing UnsignedInteger somewhere where a regular integer is expected.

I think the current behavior was introduced by trying to emulate C, but Python is not C. We need to be compatible with Python, not C. If C behavior is desired, it must be done using functions like `uneg`, not using intrinsic integer operators (which should rather behave like CPython does).

**Comment by certik** [comment]
The "-" is two's complement, so
```
-(1) = -1
-(2) = -2
-(-1) = 1
-(-2) = 2
```
The "~" is one's complement, so:
```
~(1) = -2
~(2) = -3
~(-2) = 1
~(-3) = 2
```
And in Python it also does:
```
~(0) = -1
~(-1) = 0
```

The relation between "-" and "~" is:
```
~x = -x - 1
-x = ~x + 1
```

**Comment by certik** [comment]
As a consequence, since `~x = -x-1`, this operation is by definition not supported for unsigned integers, because `~` applied to a non-negative number is negative, outside of range of unsigned. So to fix this:

* [ ] make LPython give a nice error message for `~` applied to unsigned, saying the result is out of range and providing suggestions how to obtain this operation (by properly casting to signed first, and then applying `~`)
* [ ] investigate if we need `uneg` intrinsic function, or if the workaround via casting to signed is good enough.

**Comment by certik** [comment]
Example: this
```
u: u16 = u16(255)
u = ~u
```
will not compile. Must be rewritten to:
```
u: u16 = u16(255)
u = u16(~i16(u)+2**16)
```
This is not super easy to type, so we could provide casting from signed to unsigned with wrap around, such as:
```
u: u16 = u16(255)
u = u16_wrap(~i16(u))
```

**Comment by certik** [comment]
The error message for:
```
u: u16 = u16(255)
u = ~u
```
Could be:
```
The ~ operation is out of range for u16.
u = ~u
    ^^ help: cast to signed integer first: ~i16(u); if you want to wraparound, do u16_wrap(~i16(u))
```

**Comment by Shaikh-Ubaid** [comment]
It seems using `~` on unsigned integers, LPython would be able to print an error, but I think CPython would run (and produce a negative value). Is it fine that LPython fails and CPython runs? Should not CPython also support checks for runtime overflow for unsigned integers?

**Comment by Shaikh-Ubaid** [comment]
What should be the behaviour for casting a negative integer to unsigned integer in LPython as well as CPython. For example, what should be the output of the following in CPython and LPython.

```Python
print(u16(-5))
```

**Comment by Shaikh-Ubaid** [comment]
Also, do we need to support runtime checks for binary operations on integers as well as unsigned integers? Is it a part of this issue?

**Comment by Shaikh-Ubaid** [comment]
With respect to this https://github.com/lcompilers/lpython/issues/2173#issuecomment-1639151599, similar to LPython, should CPython catch and report overflow errors?

**Comment by Shaikh-Ubaid** [comment]
Here https://github.com/lcompilers/lpython/issues/2173#issuecomment-1638945575 we discussed about `u16_wrap(~u)` for CPython. We currently have `bitnot_u16(u)` in place of it. Please share if it is fine.

**Comment by Shaikh-Ubaid** [comment]
I think with merging of https://github.com/lcompilers/lpython/pull/2189 we would complete this issue.
