### ISSUE TITLE
Add to your list of compilers?

### ISSUE THREAD

**Issue by gabrielsroka** [lcompilers/lpython#2219]
https://github.com/brython-dev/brython
https://github.com/TranscryptOrg/transcrypt

**Comment by certik** [comment]
@gabrielsroka awesome, thanks! I added both, it will appear online soon. I've heard about Brython, but not Transcrypt. If you discover any other compiler, please let us know.

**Comment by gabrielsroka** [comment]
Maybe
https://github.com/skulpt/skulpt

**Comment by certik** [comment]
Thanks, I added it in https://github.com/lcompilers/lpython.org-deploy/pull/39.
