### ISSUE TITLE
Implement list reserve

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#2233]
Here is how to use it:
```python
from lpython import reserve
def dijkstra_shortest_path(n: i32, source: i32) -> i32:
    i: i32; j: i32; v: i32; u: i32; mindist: i32; alt: i32; dummy: i32; uidx: i32
    dist_sum: i32;
    graph: list[i32] = []
    dist: list[i32] = []
    reserve(graph, n*n)
```
In CPython emulation this will be an empty function (no-op), in LPython we reserve the memory for this list, similar to reserve in C++, for performance.

**Comment by certik** [comment]
I think we can use the same function `reserve` for dicts and sets too, later on.

**Comment by czgdp1807** [comment]
Closing this in favour of #2232
