### ISSUE TITLE
Could not find the module 'lpython'

### ISSUE THREAD

**Issue by DeathBeastLLC** [lcompilers/lpython#2234]
I successfully built lpython using the MSVC Compiler from Visual Studio 2019.
I've ran the run_tests.py file which fails at: `runtime_errors/test_assert_01.py * run_dbg`
A hello world program works, but anything depending on base Python modules throws an error.
An example of this issue is when you run the expr2.py file from examples folder.

Command: `.\inst\bin\lpython .\examples\expr2.py`

Output:
```
semantic error: Could not find the module 'lpython'. If an import path is available, please use the `-I` option to specify it
 --> .\examples\expr2.py:1:1
  |
1 | from lpython import i32
  | ^^^^^^^^^^^^^^^^^^^^^^^


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that must be fixed).
```
Am i supposed to manually find python modules and include them ?
Thanks in advance.

**Comment by Shaikh-Ubaid** [comment]
Thanks @DeathBeastLLC for trying out LPython!

>I successfully built lpython using the MSVC Compiler from Visual Studio 2019.

Please, could you try using the `lpython` binary stored in the `src/bin` directory and share if it works. For example:
```bash
.\src\bin\lpython .\examples\expr2.py
```

**Comment by certik** [comment]
@DeathBeastLLC thanks for trying it out. The Windows support is currently rough, compared to Linux/macOS. Try @Shaikh-Ubaid's suggestion. You can also try installing lpython using conda on Windows and see if that helps.

**Comment by DeathBeastLLC** [comment]
Here's an update to the issue.
Using the LPython binary from src folder throws a different kind of error now.

Command: `.\src\bin\lpython.exe .\examples\expr2.py`

Output:
```The command 'link /NOLOGO /OUT:.\examples\expr2.out .\examples\expr2.out.tmp.o D:\Python\LPython\src\bin/../runtime\lpython_runtime_static.lib > NUL' failed.```

**Comment by certik** [comment]
@DeathBeastLLC thanks for trying it out. It would have to be debugged. The expr2 example works on Windows, since we test it by the CI here: https://github.com/lcompilers/lpython/blob/3927b92ef449fefb767d3c02d6821cc8f7b06dca/ci/test.xsh#L9

Make sure you have MSVC loaded, see here: https://github.com/lcompilers/lpython/blob/3927b92ef449fefb767d3c02d6821cc8f7b06dca/.github/workflows/CI.yml#L113.

Try to do exactly what the CI does. That should work. Then you can try to deviate from it and see.

**Comment by certik** [comment]
@DeathBeastLLC did you resolve it? If so, post here what worked for you, in case others encounter the same problem.

**Comment by certik** [comment]
@DeathBeastLLC perfect, thank you! I am glad you got it working and thanks for all the tips.

**Comment by liudonghua123** [comment]
I have the similar issue when I tried to execute `inst\bin\lpython.exe examples\expr2.py -o expr2.exe` after success build on windows.

```
(lp) D:\code\python\lpython>inst\bin\lpython.exe examples\expr2.py -o expr2.exe
semantic error: Could not find the module 'lpython'. If an import path is available, please use the `-I` option to specify it
 --> examples\expr2.py:1:1
  |
1 | from lpython import i32
  | ^^^^^^^^^^^^^^^^^^^^^^^


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that must be fixed).

(lp) D:\code\python\lpython>
(lp) D:\code\python\lpython>cat examples\expr2.py
from lpython import i32

def main0():
    x: i32
    x = (2+3)*5
    print(x)

if __name__ == "__main__":
   main0()

(lp) D:\code\python\lpython>
```

I also tried `src\bin\lpython.exe examples\expr2.py -o expr2.exe`.

![image](https://github.com/lcompilers/lpython/assets/2276718/19551ad1-ad04-4d47-822e-205cbc280d2c)

![image](https://github.com/lcompilers/lpython/assets/2276718/bcee1ed0-f316-4029-a9ea-fa42cc8efaf5)

**Comment by Thirumalai-Shaktivel** [comment]
Currently, we only support fewer modules like `math`, `numpy`, `sympy`, ...

**Comment by liudonghua123** [comment]
> > [#2234 (comment)](https://github.com/lcompilers/lpython/issues/2234#issuecomment-1664188029)
> 
> @liudonghua123 Are you trying it on the `mini forge` or `anaconda` prompt?
> 
> Edit: Also, Try to specify the path using `-I`. `inst\bin\lpython.exe -I. examples\expr2.py` and see if it fixes the issue.
> 
> Edit 2: Try installing miniforge using the Windows installer from https://github.com/conda-forge/miniforge and run on that prompt. I think that would work.

I have used `conda` of miniforge to activated the environment. And I also tried `-I.`, it's the same error.

```
D:\code\python\lpython>conda.bat activate lp

(lp) D:\code\python\lpython>inst\bin\lpython.exe -I. examples\expr2.py
semantic error: Could not find the module 'lpython'. If an import path is available, please use the `-I` option to specify it
 --> examples\expr2.py:1:1
  |
1 | from lpython import i32
  | ^^^^^^^^^^^^^^^^^^^^^^^


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that must be fixed).

(lp) D:\code\python\lpython>
```

**Comment by Thirumalai-Shaktivel** [comment]
The image from this comment: https://github.com/lcompilers/lpython/issues/2234#issuecomment-1664188029, looks like you are using a command prompt. Can you please try to build and execute LPython on the mini forge prompt?

Also, check out
> https://github.com/lcompilers/lpython/issues/2234#issuecomment-1660102549
Edit: Tried again and now it WORKS, it looks like Powershell couldn't run some commands. So for the solution is to make sure to use miniforge prompt ( or anaconda prompt ) when building or running lpython.

**Comment by liudonghua123** [comment]
I tried Miniforge primpt, but it's the same.

<img width="866" alt="image" src="https://github.com/lcompilers/lpython/assets/2276718/ae871082-f862-4bbb-87fa-cd02e864fc24">

**Comment by DeathBeastLLC** [comment]
Here is a step by step process from zero that should work for you:
- Open Miniforge Prompt
- Run Command : `call "C:/Program Files (x86)/Microsoft Visual Studio/<VERSION>/<EDITION>/VC/Auxiliary/Build/vcvars64.bat"`
NOTE: VERSION is your Visual Studio Version. Example: 2019. EDITION: is your Visual Studio Edition. Example: Community
- Confirm That MSVC Works By Calling Either: `cl /?` or `link /?`
- Clone LPython Repo Or Release
- Create Conda Environnement And Activate It ( From Installation Guide )
- Run `call build0.bat` And `call build1.bat`
- Now Instead Of Using The Binary File From Inst, Try Using The Binary From src Folder (Should Be Located At: `src\bin\lpython.exe`)
I hope this fixes your problem.

**Comment by Thirumalai-Shaktivel** [comment]
Thanks, @DeathBeastLLC for the details steps. Yup, that would work!!

@liudonghua123, The issue is, the lpython binary was built from the command prompt. But, we have to build it in the mini forge prompt.
For that, we will do the clean build in the mini forge prompt using the following steps.
```console
$ git clean -dfx
$ call "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd" -arch=x64
$ call build0.bat
$ call build1.bat # After the build was successful, try:
$ inst\bin\lpython examples\expr2.py
```
I hope this would work, any issues let us know. 

Thank you!

**Comment by dlee992** [comment]
Having the same issue on Mac M2, after `You can install it using Conda (conda install -c conda-forge lpython)`, it shows install works:
```
(base) ➜  ~ conda list lpython
# packages in environment at /opt/homebrew/anaconda3:
#
# Name                    Version                   Build  Channel
lpython                   0.19.0               ha614eb4_0    conda-forge
```
but can't import it:
```
(base) ➜  ~ python -c "import lpython"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'lpython'
```

I found conda saves the lpython shared library under `..../bin/lpython`, and in site-packages, no package named `lpython`.

**Comment by certik** [comment]
@dlee992 I think that's a different error. The current lpython conda package does not install `lpython` systemwide. This is a very good point, I think we should do that! Currently you have to something like this:
```console
$ PYTHONPATH="$(lpython --get-rtl-dir)/lpython" python -c "import lpython"
$
```
This works for me on M1.

**Comment by liudonghua123** [comment]
> @dlee992 I think that's a different error. The current lpython conda package does not install `lpython` systemwide. This is a very good point, I think we should do that! Currently you have to do something like this:
> 
> ```
> $ PYTHONPATH="$(lpython --get-rtl-dir)/lpython" python -c "import lpython"
> $
> ```
> 
> This works for me on M1.
> 
> I created an issue for this at #2265.

Thanks, I tried your methods, it works for me. I need to change `inst\bin\lpython.exe` to `src\bin\lpython.exe`. What's difference between them?

```
(lp) D:\code\python\lpython>inst\bin\lpython --get-rtl-dir
D:\code\python\lpython\inst\bin/../share/lpython/lib

(lp) D:\code\python\lpython>
(lp) D:\code\python\lpython>inst\bin\lpython.exe examples\expr2.py -o examples\expr2.exe
semantic error: Could not find the module 'lpython'. If an import path is available, please use the `-I` option to specify it
 --> examples\expr2.py:1:1
  |
1 | from lpython import i32
  | ^^^^^^^^^^^^^^^^^^^^^^^


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that must be fixed).

(lp) D:\code\python\lpython>set PYTHONPATH=D:\code\python\lpython\inst\share\lpython\lib\lpython

(lp) D:\code\python\lpython>echo %PYTHONPATH%
D:\code\python\lpython\inst\share\lpython\lib\lpython

(lp) D:\code\python\lpython>inst\bin\lpython.exe examples\expr2.py -o examples\expr2.exe
semantic error: Could not find the module 'lpython'. If an import path is available, please use the `-I` option to specify it
 --> examples\expr2.py:1:1
  |
1 | from lpython import i32
  | ^^^^^^^^^^^^^^^^^^^^^^^


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that must be fixed).

(lp) D:\code\python\lpython>src\bin\lpython.exe examples\expr2.py -o examples\expr2.exe

(lp) D:\code\python\lpython>examples\expr2.exe
25

(lp) D:\code\python\lpython>ldd examples\expr2.exe
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7fff5b5f0000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7fff5a490000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7fff58f60000)
(lp) D:\code\python\lpython>
```
