### ISSUE TITLE
Provide binaries for platforms where Conda is not desired

### ISSUE THREAD

**Issue by joaompinto** [lcompilers/lpython#2248]
I would like to get lpython as a binary for systems where conda is not desired to be installed.

**Comment by certik** [comment]
What platform are you on?

**Comment by joaompinto** [comment]
Windows, nevertheless on this specific system I have no intent to install conda/mamba. I would be willing to create a request to make lpython available vis Scoop for Windows assuming the lpython release itself could provide the binaries compiled with the scoop provided GCC

**Comment by certik** [comment]
We will create binaries for all platforms once we reach beta. Until then I don't want to spread too thin with testing custom binaries on all platforms, so we only support building from source and then conda as a reference "binary". However if people are willing to contribute and maintain binary generation at the CI, we'll be happy to accept pull requests.

**Comment by joaompinto** [comment]
Fair enough, closing for the time being.
Thanks for the feedback.
