### ISSUE TITLE
Missing MicroPython from the comparison

### ISSUE THREAD

**Issue by Oppen** [lcompilers/lpython#2256]
I saw at Phoronix the authors are interested in adding any possible missing interpreter/compiler for Python. Seeing not all of them are 100% compatible with CPython, I assume [MicroPython](https://micropython.org/) should also be counted in.

(I would have mentioned it in Phoronix but I deleted my account to avoid wasting time on flamewars)

**Comment by certik** [comment]
@Oppen thanks! I just added it in. I knew about MicroPython, but forgot about it. If you find any other compiler that we missed, please let us know.
