### ISSUE TITLE
why `\v` is getting converted into `\u000b` during asr_to_c conversion 

### ISSUE THREAD

**Issue by Agent-Hellboy** [lcompilers/lpython#2375]
I got below error while using `ch=='\v'` 
```
/home/runner/work/lpython/lpython/integration_tests/_lpython-tmp-test-c/test_str_attributes.c: In function ‘__lpython_overloaded_0___lpython_str_isspace’:
/home/runner/work/lpython/lpython/integration_tests/_lpython-tmp-test-c/test_str_attributes.c:1991:167: error: \u000b is not a valid universal character
 1991 |         if (strcmp(ch, " ")  !=  0 && strcmp(ch, "\t")  !=  0 && strcmp(ch, "\n")  !=  0 && strcmp(ch, "\r")  !=  0 && strcmp(ch, "\\f")  !=  0 && strcmp(ch, "\u000b")  !=  0) {
      |     
  ```
  please debug why?

Edit: `isspace` issue was related to name mangling, so I removed it.

**Comment by Shaikh-Ubaid** [comment]
The following might fix it:
```diff
diff --git a/src/libasr/string_utils.cpp b/src/libasr/string_utils.cpp
index 073167d16..55e5a6b2a 100644
--- a/src/libasr/string_utils.cpp
+++ b/src/libasr/string_utils.cpp
@@ -142,6 +142,7 @@ std::string str_escape_c(const std::string &s) {
             case '\n': o << "\\n"; break;
             case '\r': o << "\\r"; break;
             case '\t': o << "\\t"; break;
+            case '\v': o << "\\v"; break;
             default:
                 if ('\x00' <= *c && *c <= '\x1f') {
                     o << "\\u"
```

**Comment by Thirumalai-Shaktivel** [comment]
MRE: 
```py
from sympy import pi, Symbol, S

def main0():
    x: str = 'Hel\vlo'
    print(x)

main0()
```
LLVM
```console
$ lpython examples/expr2.py
Hel
   lo
```
C
```console
$ lpython examples/expr2.py --backend=c
expr2__tmp__generated__.c:17:30: error: universal character name refers to a control character
    _lfortran_strcpy(&x, "Hel\u000blo", 1);
                             ^~~~~~
1 error generated.
The command 'gcc -o expr2.out expr2__tmp__generated__.c  -I /Users/thirumalai/Open_Source/lpython/src/bin/../libasr/runtime -L"/Users/thirumalai/Open_Source/lpython/src/bin/../runtime" -Wl,-rpath,"/Users/thirumalai/Open_Source/lpython/src/bin/../runtime" -llpython_runtime -lm' failed.
```

**Comment by Agent-Hellboy** [comment]
> The following might fix it:
> 
> ```diff
> diff --git a/src/libasr/string_utils.cpp b/src/libasr/string_utils.cpp
> index 073167d16..55e5a6b2a 100644
> --- a/src/libasr/string_utils.cpp
> +++ b/src/libasr/string_utils.cpp
> @@ -142,6 +142,7 @@ std::string str_escape_c(const std::string &s) {
>              case '\n': o << "\\n"; break;
>              case '\r': o << "\\r"; break;
>              case '\t': o << "\\t"; break;
> +            case '\v': o << "\\v"; break;
>              default:
>                  if ('\x00' <= *c && *c <= '\x1f') {
>                      o << "\\u"
> ```

should I add a PR for the same and revert my changes?

**Comment by Shaikh-Ubaid** [comment]
>should I add a PR for the same and revert my changes?

Since it is just a one-line change, I would include it in existing PR https://github.com/lcompilers/lpython/pull/2373.

**Comment by Agent-Hellboy** [comment]
> > should I add a PR for the same and revert my changes?
> 
> Since it is just a one-line change, I would include it in existing PR #2373.

okay
