### ISSUE TITLE
Add `@interface` decorator

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#239]
Currently we define a function interface using:
```python
def complex(x: f64, y: f64) -> c64:
    pass
```
But that is the same syntax as for an empty function. I think we should add an `@interface` decorator into `ltypes`, which would probably raise an exception if the function was ever being called (by CPython). In LPython, that would declare an interface, meaning the function with that name must be provided in global scope at some point before compiling to LLVM.

**Comment by Smit-create** [comment]
Do you mean something like this?

```py
def interface():
    raise Exception('Unexpected to be called')

@interface
def complex(x: f64, y: f64) -> c64:
    pass
```

Internally, we will handle `lpython` when it sees an `interface` operator, and CPython is not expected to call this function at all.

**Comment by certik** [comment]
Yes, exactly. (The CPython implementation I think has to be a nested function thought.)

**Comment by Smit-create** [comment]
Okay, I will try to get it implemented.
