### ISSUE TITLE
Incorrect Error message in ASRVerfiy

### ISSUE THREAD

**Issue by Shaikh-Ubaid** [lcompilers/lpython#2392]
I think this should be `"Dependency " + found_dep +  " is not* inside symbol table " `

_Originally posted by @Shaikh-Ubaid in https://github.com/lcompilers/lpython/pull/2167#discussion_r1370345894_

**Comment by Shaikh-Ubaid** [comment]
@arteevraina would you like to tackle this?

**Comment by arteevraina** [comment]
> @arteevraina would you like to tackle this?

Sure.
