### ISSUE TITLE
Unused variable for the do loop created by array_op

### ISSUE THREAD

**Issue by Thirumalai-Shaktivel** [lcompilers/lpython#2403]
Sometimes, the cases like the following created unused variable:
```fortran
program expr2
implicit none
integer :: x(3)
x = 23
end program
```

`--show-fortran --pass=array_op`
Here `__1_v` is unused.
```fortran
! Fortran code after applying the pass: array_op
program expr2
implicit none
integer(4) :: __1_t
integer(4) :: __1_v
integer(4), dimension(3) :: x
__1_v = lbound(x, 1)
do __1_t = lbound(x, 1), ubound(x, 1)
    x(__1_t) = 23
    __1_v = __1_v + 1
end do
end program expr2
```

**Comment by certik** [comment]
There are two solutions:
* Add a pass to remove unused variables, functions (we already have this one), etc.
* Make the `array_op` pass not create unused variables

I think we need that first point anyway. The second point is thus optional to speedup compilation time.
