### ISSUE TITLE
Could not find the module 'lpython'. If an import path is available, please use the `-I` option to specify it

### ISSUE THREAD

**Issue by ujjwaltwitx** [lcompilers/lpython#2435]
Building lpython on windows following the guide provided on the github page throws this error.
![Screenshot 2023-11-28 122838](https://github.com/lcompilers/lpython/assets/85453780/1c2169f6-d0c1-4376-82d9-1dc8bd0854f1)

**Comment by certik** [comment]
Run it from `src/bin/lpython`, not `inst/bin/lpython`. Then it should work.

**Comment by ujjwaltwitx** [comment]
> Run it from `src/bin/lpython`, not `inst/bin/lpython`. Then it should work.
This works. The documentation should change to reflect this.

**Comment by certik** [comment]
> This works. The documentation should change to reflect this.

@ujjwaltwitx awesome, I am glad it works. Do you want to submit a PR to the documentation to fix it?

**Comment by ujjwaltwitx** [comment]
Yes, I definitely want to submit a PR

**Comment by ujjwaltwitx** [comment]
I have raised a PR to solve this issue. Please review it if possible.
