### ISSUE TITLE
CI for testing through macos seems flaky

### ISSUE THREAD

**Issue by anutosh491** [lcompilers/lpython#2455]
The CI yesterday was passing at some attempts and failing otherwise. At a couple of instances I saw it is also running infinitely (https://github.com/lcompilers/lpython/actions/runs/7438892349/job/20243305980)

**Comment by certik** [comment]
Also discussed at https://lfortran.zulipchat.com/#narrow/stream/197339-general/topic/CI.20for.20testing.20through.20macos.20seems.20flaky.20for.20Lpython.

**Comment by certik** [comment]
This is now "fixed" by removing the tests. See https://github.com/lcompilers/lpython/issues/2520 for the proper fix.
