### ISSUE TITLE
symbolics_11.py and symbolics_14.py produce invalid code

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#2469]
How to reproduce:
```console
$ lpython symbolics_14.py --show-c
[...]
// Implementations
void mmrv(void* x, struct list_CPtr *_lpython_return_variable)
{
    struct list_CPtr l1;
    struct list_CPtr constname0;
    list_init_CPtr(&constname0, 1);
    constname0.data[0] = x;
    constname0.current_end_point = 1;
    list_deepcopy_CPtr(&constname0, &l1);

    list_deepcopy_CPtr(&l1, _lpython_return_variable);

}
```
The line `constname0.data[0] = x;` is incorrect, instead it should be `basic_assign(constname0.data[0], x);`.

The current code thus contains dangling points, so it might or might not segfault.

**Comment by certik** [comment]
Exactly the same problem is in `symbolics_11.py`:
```console
$ lpython symbolics_11.py --show-c
[...]
// Implementations
void test_extraction_of_elements()
{
    int64_t _ele1;
    int64_t _ele2;
    int64_t _ele3;
...
    constname0.data[0] = x;
    constname0.data[1] = stack0;
    constname0.data[2] = stack1;
    constname0.data[3] = stack2;
...
```

**Comment by certik** [comment]
To fix this, here is a reference code that does the right thing: https://github.com/lcompilers/lpython/pull/2465, so all we need to do now is to ensure the symbolic pass is generating the same ASR as `symbolics_15` does.

In particular, instead of a simple assignment, it needs to call `basic_assign`.

**Comment by anutosh491** [comment]
Can be closed as the issue has been correctly fixed through https://github.com/lcompilers/lpython/pull/2465 & https://github.com/lcompilers/lpython/pull/2477
