### ISSUE TITLE
float to int conversion doesn't work

### ISSUE THREAD

**Issue by Abdullahjavednesar** [lcompilers/lpython#254]
Example:
```
def f():
    i: f64
    j: i32
    i = 300.27
    j = int(i)
    print(i, j)

f()
```

output:

```
~/owork/lpython> ./src/bin/lpython integration_tests/test_math1.py --show-stacktrace  
ld: warning: dylib (/Users/anesa00/owork/lpython/src/runtime/liblfortran_runtime.dylib) was built for newer macOS version (11.5) than being linked (11.0)
~/owork/lpython> ./a.out                                                            
  300.26999999999998181 1
```

**Comment by Smit-create** [comment]
I see, we have this issue. See: https://github.com/lcompilers/lpython/blob/main/integration_tests/test_builtin_int.py. I was unable to figure out the exact reason for this.

**Comment by Oshanath** [comment]
@Smit-create could you please show me where the int() function is implemented in the python_ast_to_ast.cpp file? In the builtin.py file it says that this function is handled by llvm and if so, should be located in this file right?

**Comment by certik** [comment]
These conversions have to be fixed properly by inserting a proper cast into ASR.
