### ISSUE TITLE
Excess lines in `--show-python` output

### ISSUE THREAD

**Issue by Shaikh-Ubaid** [lcompilers/lpython#2583]
Excess lines here should not be present. I think this can be handled in a separate PR.

_Originally posted by @Shaikh-Ubaid in https://github.com/lcompilers/lpython/pull/2580#discussion_r1515743191_

**Comment by Shaikh-Ubaid** [comment]
@khushi-411 you can work on it.

**Comment by khushi-411** [comment]
Yes! I'm working on this!
