### ISSUE TITLE
[Help] How can I solve call build1.bat build Failure on Windows? And how can I use lpython?

### ISSUE THREAD

**Issue by Foxchandaisuki** [lcompilers/lpython#2610]
We have an install guide here but no use guide...

And I can't find how to solve call build1.bat build Failure.

**Comment by kmr-srbh** [comment]
I think this is not the correct place to raise this issue. You can post about the error along with the stacktrace, in the Zulip group here: https://lfortran.zulipchat.com/

Please close this issue.
