### ISSUE TITLE
How are imported libraries treated in LPython program?

### ISSUE THREAD

**Issue by Foxchandaisuki** [lcompilers/lpython#2681]
As I heard, in case of Mojo language, which is LPython's competitor, the python libraries imported in Mojo program are not AOT compiled and need to be interpreted at runtime, so the computer running Mojo program importing Python libraries must have that libraries installed on it.

How about LPython? It does same to the imported Python libraries? or they also got AOT compiled and the computer running the program are not required to install the libraries on it?

**Comment by kmr-srbh** [comment]
Hello! Since you have posted the above query in our Zulip organization, I request you to close this issue.
