### ISSUE TITLE
I hope we had a discord or something similar with it that makes us communicate in real-time.

### ISSUE THREAD

**Issue by Foxchandaisuki** [lcompilers/lpython#2682]
Communicating only via Github issue is too painful to wait the comment written.

**Comment by kmr-srbh** [comment]
@Foxchandaisuki thanks for this! I see that you are already part of our Zulip organization at https://lfortran.zulipchat.com/. Please text us there in the "lpython" stream to discuss any ideas you may have or issues you face. :+1:

**Comment by kmr-srbh** [comment]
@Foxchandaisuki since you are aware of our Zulip organization now, I think this issue is resolved. I request you to close it.
