### ISSUE TITLE
Adding a List to ASR as a dedicated container type

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#272]
Per my comment here:

https://github.com/lcompilers/lpython/issues/270#issuecomment-1075213149

The fundamental semantic difference between an array and a list:

Array: It seems that semantically a multidimensional array is not a container in a sense that it only can contain elements of basic type like integer or real, but not "allocatable type", so you cannot have an array of allocatable character (array of strings), or allocatable arrays (array of different length arrays, so called "ragged array". The main purpose of a multidimensional array is a very efficient representation of uniform types and the fastest operations, but it is not meant as a container of "diverse types".

List: List can contain allocatable types, so it can represent a list of strings as a list of of allocatable characters, or ragged arrays (a list of lists or a list of allocatable arrays). You pay for this extra flexibility with a lowered performance. Also a list is fundamentally 1D.

It seem that whenever you can use an array, you should use it because it is faster, but it you need flexibility with each element having a different size, then you can use a list. Since the type of the list must be known at compile time (for efficiency and type checking), it seems the elements have to be of the same type, but they can be allocatable, thus having different size. That might cover most use cases. If different types are needed, one would have to use a list of structs.

In Python, it seems the most common use cases for lists that cannot be represented as arrays, are:

* List of strings: any string manipulation needs it, such as split(), str.join(), readlines(), etc.
* Ragged arrays: e.g. reading rows of numbers (or strings) from a file, where each row can have a different length

As a container (just like a struct), when the list goes out of scope, it deallocates all its elements (if they are allocatable).

**Comment by namannimmo10** [comment]
I definitely agree.  +1 to add the list as a separate container in the ASR.

**Comment by namannimmo10** [comment]
I am gonna work on it.

**Comment by certik** [comment]
Idea: LPython should provide a hint if you declare a List in a way that can be declared as a 1D array. So for a function accepting `List[i32]` as an argument type, the compiler should suggest to use `Array[i32,:]` (or LPython's syntactic sugar `i32[:]`) instead. We'll have to figure out how to disable the hint if a list is really intended, perhaps `Annotated[List[i32], NoWarning]`.

Example of List types that cannot be done using arrays are: `List[List[i32]]`, `List[Annotated[i32[:], Allocatable]]`, `List[str]`, etc.
