### ISSUE TITLE
CI sometimes passes when it fails

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#280]
This is an example where LPython clearly failed:

https://github.com/lcompilers/lpython/runs/5671467982?check_suite_focus=true

But the CI succeeded... So we need to

* [x] reproduce this
* [x] figure out why it happens
* [x] fix it

**Comment by Smit-create** [comment]
This seems to be fixed now.

**Comment by certik** [comment]
Yes, I think this was fixed by #299.
