### ISSUE TITLE
Implement `max` and `min` intrinsic functions

### ISSUE THREAD

**Issue by namannimmo10** [lcompilers/lpython#306]

**Comment by purna135** [comment]
I'd like to work on this issue, but I'm not sure where to put the code for the `min` and `max` functions if I were to implement them.

**Comment by purna135** [comment]
should it be `runtime/math.py` ?

**Comment by certik** [comment]
@purna135 yes, you can work on any issue you want, simply send a PR, you don't have to ask for permission. Yes in `src/runtime` (although in `lpython_builtin` instead of `math`), this particular issue was fixed in #335, so you can look there for the details.

**Comment by purna135** [comment]
Thank you @certik
