### ISSUE TITLE
Interactivity

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#329]
Make LPython work in an interactive prompt.

Copy how LFortran does it. We have to remember a symbol table, and compile each prompt as we go. LFortran has all the infrastructure, I think it's not difficult to add to LPython.

**Comment by deadtik** [comment]
Can I get the documentation for LFortran?

**Comment by certik** [comment]
https://docs.lfortran.org/

**Comment by Vipul-Cariappa** [comment]
We discussed the following during the last meeting:

Currently, the interactive shell is implemented in LFortran by assigning the parent of a symbol table to the symbol table of the previously executed cell's symbol table. This shadows the previous definition(s). It is advantageous as it allows rewriting symbols. We should try taking a similar approach while implementing the interactive shell for LPython.

Hopefully, we implement the interactive shell such that it can be shared with multiple frontends, i.e. combine LPython and LFortran's implementation. Try using the same implementation with LC frontend.
