### ISSUE TITLE
Setup environment.yml for creating a development Conda environment

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#350]
Reported by @czgdp1807 at https://github.com/lcompilers/lpython/pull/234#issuecomment-1093855868:

IMO, we can also an environment.yml file separately under the project root. Reason being, it helps new devs to quickly setup by just executing, conda create env -f environment.yml, instead of going through a bunch links on the web to figure how to do it all. In any case having such a file would be really helpful.

**Comment by Smit-create** [comment]
We already have `environment.yml` here: https://github.com/lcompilers/lpython/blob/main/ci/environment.yml.

**Comment by czgdp1807** [comment]
That's for CI, I think? May be provide 2 options to the users, first if they want they can create an environment same as CI locally on their machine or second, use the environment.yml file merged in this PR. Reason being I don't use any dependency in the file you have linked while developing lfortran/lpython. So, there may be other who might not want to add un-wanted dependencies in their lfortran/lpython environment.
