### ISSUE TITLE
Bug in Python_ast.h generation

### ISSUE THREAD

**Issue by Thirumalai-Shaktivel** [lcompilers/lpython#371]
https://github.com/lcompilers/lpython/blob/1bb9225d3576c06eba16422d59aa01e1a3fd5cd0/grammar/Python.asdl#L45
Should generate the following:
```c++
    struct Import_t // Constructor
    {
        const static stmtType class_type = stmtType::Import;
        typedef stmt_t parent_type;
        stmt_t base;
        alias_t** m_names; size_t n_names; // Sequence                        <------------
    };
```
but instead it generates:
```c++
    struct Import_t // Constructor
    {
        const static stmtType class_type = stmtType::Import;
        typedef stmt_t parent_type;
        stmt_t base;
        alias_t* m_names; size_t n_names; // Sequence                           <------------
    };
```
The same goes for other Product Type

**Comment by certik** [comment]
I think this is correct. `alias` is defined as `    alias = (identifier name, identifier? asname)`, so it is a struct, and so only one pointer, not double pointer should be generated.

**Comment by Thirumalai-Shaktivel** [comment]
I see. Now I understand why alias_t must be a single pointer but not a double pointer.
Thanks for clarifying.

**Comment by certik** [comment]
I did it this way for performance reasons. It doesn't have to be that way, but it's faster if it is done that way.
