### ISSUE TITLE
Proposal to create separate files for attribute

### ISSUE THREAD

**Issue by Smit-create** [lcompilers/lpython#431]
As we have started supporting some of the basic Python data types such as `list`, `dict`, `set`, etc, we also plan to allow operations on these data types such as `append`, `remove`, `add`, `insert`, etc. This in python is done with the help of attributes. So, in order to keep the design more compact and cleaner, I am thinking to separate out the attributes part in a different file(much like `compile_time_eval`) and use a map to access them. Let me know your views and suggestions.

Presently, we are just writing everything here:
https://github.com/lcompilers/lpython/blob/a1d726f9e2f740c09a1fe7123e3a7d215578da66/src/lpython/semantics/python_ast_to_asr.cpp#L2424

**Comment by certik** [comment]
Great idea. If you can figure out how to simplify the `visit_Expr` visitor where all this logic is, that would be awesome. Your proposal seems reasonable. If you want, you can go ahead and try to implement it.

**Comment by Smit-create** [comment]
Yeah, I think `visit_Expr` and `visit_Call` are the two main parents of `visit_Attribute`. So, I'll try to separate the logic out of them.
