### ISSUE TITLE
LLVM: List implementation

### ISSUE THREAD

**Issue by Smit-create** [lcompilers/lpython#488]
Currently, we implemented a small prototype of python lists using runtime function and calling back into C. IMHO, this approach is easier to implement but might not be feasible in long term. See #484 

We should discuss alternative approaches to it.  One way that seems appropriate is suggested here: https://github.com/lcompilers/lpython/pull/484#issuecomment-1125170492 by @certik

**Comment by Smit-create** [comment]
Can this be useful? https://llvm.org/doxygen/ilist_8h_source.html

**Comment by certik** [comment]
I am hoping we can just use C libraries for the LLVM backend's runtime library. If we use a C++ library, such as the `ilist` above, then we need to distribute the C++ runtime library also.

**Comment by namannimmo10** [comment]
How are we going to move forward with this? It seems to me that we won't go much far with the current approach. Should we try out the LLVM implementations for `list[i32]` and `set[i32]`?

**Comment by certik** [comment]
Yes, for lists ultimately I think we should implement them in LLVM directly, by creating a new header file with auxiliary functions that we need, so that it is easy to do it from the main `asr_to_llvm` file.
