### ISSUE TITLE
--fast miscompiles fibonacci

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#519]
```
from ltypes import i64

def fib(n: i64) -> i64:
    if n < 2:
        return n
    else:
        return fib(n - 1) + fib(n - 2)

def main():
    ans: i64
    x: i64
    x = 40
    ans = fib(x)
    print(ans)

main()
```
It works in Debug mode but not in Release mode:
```console
$ lpython b.py && ./a.out
102334155
$ lpython --fast b.py && ./a.out
$
```

**Comment by certik** [comment]
It's a bug in the `inline_function` ASR pass. This is a workaround until we fix it:
```
--- a/src/libasr/codegen/asr_to_llvm.cpp
+++ b/src/libasr/codegen/asr_to_llvm.cpp
@@ -4540,7 +4540,7 @@ Result<std::unique_ptr<LLVMModule>> asr_to_llvm(ASR::TranslationUnit_t &asr,
         pass_replace_sign_from_value(al, asr, rl_path);
         pass_replace_div_to_mul(al, asr, rl_path);
         pass_replace_fma(al, asr, rl_path);
-        pass_inline_function_calls(al, asr, rl_path);
+//        pass_inline_function_calls(al, asr, rl_path);
     }
 
     v.nested_func_types = pass_find_nested_vars(asr, context,
```

**Comment by czgdp1807** [comment]
I think `fib` should never get inlined in the first place. So input and output ASR for inline pass should be same. It shouldn’t be that hard to fix it. Let @faze-geek try fixing it until I come back.

**Comment by czgdp1807** [comment]
Any news @faze-geek on this? Did you try fixing this?

**Comment by faze-geek** [comment]
Sorry ,got busy with a prior commitment at my university . I'll look into it soon . 
You can takeover #531 if you wish .

**Comment by czgdp1807** [comment]
The bug is not with the inline function pass. It works fine. The problem is with inclusion of empty returns in the function body. See below,

```py
fib [
               (Var 2 n)] [
               (If 
                  (IntegerCompare 
                     (Var 2 n) 
                     Lt 
                     (Cast (IntegerConstant 2 
                        (Integer 4 [])) 
                        IntegerToInteger 
                        (Integer 8 []) ()) 
                     (Logical 4 []) ()) [
                  (= 
                     (Var 2 _lpython_return_variable) 
                     (Var 2 n) ()) 
                  (Return)] [
                  (= 
                     (Var 2 _lpython_return_variable) 
                     (IntegerBinOp 
                        (FunctionCall 1 fib () [
                           (
                              (IntegerBinOp 
                                 (Var 2 n) 
                                 Sub 
                                 (Cast (IntegerConstant 1 
                                    (Integer 4 [])) 
                                    IntegerToInteger 
                                    (Integer 8 []) ()) 
                                 (Integer 8 []) ()))] 
                           (Integer 8 []) () ()) 
                        Add 
                        (FunctionCall 1 fib () [
                           (
                              (IntegerBinOp 
                                 (Var 2 n) 
                                 Sub 
                                 (Cast (IntegerConstant 2 
                                    (Integer 4 [])) 
                                    IntegerToInteger 
                                    (Integer 8 []) ()) 
                                 (Integer 8 []) ()))] 
                           (Integer 8 []) () ()) 
                        (Integer 8 []) ()) ()) 
                  (Return)])]
```

Now the inline function pass was originally written and tested for LFortran (where we don't have return variables in Function but instead specify the variable in which the results will be stored). However here in LPython we are including empty return statements after storing the result in return variable. The function inlining pass while inlining copies the whole body at the call site. So, these empty returns are placed there as well. Hence, the output is never printed because the empty return is executed before the print statement. 

Inlining functions with multiple return statements in their bodies is tricky IMO. Because with every return statement it means the body below that return statement will either be ignored or executed. So what we can do is create a logical variable say, `ignore`. While inlining replace `Return` with `ignore = True`. Now, the rest of the body will be place under an if `if ignore`. So at runtime they will be executed only when no previous return statements were executed. Its a very rough solution but there might be very tricky corner cases. Like for do loop there will be different semantics to deal with return, same for if-else statements, etc.

**Comment by certik** [comment]
I think the exact same issue would happen in LFortran if you put `return` at the end of a function.

I think this is a general problem --- how to handle `return` inside a function that gets inlined. It doesn't matter where in the function the `return` happens, if there is a `return`, then we have to replace it with something else. If it is at the end of a function, then we can simply remove it. But how to handle cases like this:
```python
def f():
    if (...):
        return
    ...
```
Here we can't just inline it, we have to replace the control flow. One approach is to use the `GoTo` ASR node, that we already have. Another approach is to wrap the inlined function inside a "Block" node, and replace `return` with `exit` (I think you can exit such a node with that in Fortran). Then we can write some separate ASR passes that transform a Block statement with "exit" inside it into other control flow constructs, if needed.

**Comment by certik** [comment]
I think that's fine. (Note that we will have to support the Block statement independently of how we solve this issue.)

**Comment by faze-geek** [comment]
Hey, I surfed back on this issue and reran the code. Are you sure this issue is solved? `--fast` either returns 1 or a very large (I guess garbage) value.

```
def fib(n: i32) -> i32:
    if n < (2):
        return n
    else:
        return fib(n - (1)) + fib(n - (2))

def main():
    ans: i32
    x: i32
    x = 20
    ans = fib(x)
    print(ans)

main()
(lp) C:\Users\kunni\lpython>src\bin\lpython try.py
6765

(lp) C:\Users\kunni\lpython>src\bin\lpython --fast try.py
1 
```



```
def fib(n: i64) -> i64:
    if n < i64(2):
        return n
    else:
        return fib(n - i64(1)) + fib(n - i64(2))

def main():
    ans: i64
    x: i64
    x = i64(40)
    ans = fib(x)
    print(ans)

main()

(lp) C:\Users\kunni\lpython>src\bin\lpython try.py
102334155

(lp) C:\Users\kunni\lpython>src\bin\lpython --fast try.py
1
```
