### ISSUE TITLE
Fix an issue with a function called `main`

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#529]
This returns a non-zero exit code (but only sometimes, such as on macOS):
```python
from ltypes import i64

def main():
    x: i64
    x = 15

main()
```
The current workaround is to rename the function, such as:
```python
from ltypes import i64

def main0():
    x: i64
    x = 15

main0()
```
And the fix has to happen in the LLVM backend to rename the function automatically under the hood.

**Comment by Smit-create** [comment]
This will also be helpful in the case of CPP/C code generation.
