### ISSUE TITLE
Add integration tests for the C backend

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#544]
Currently we only test the `--show-c` with the `./run_tests.py` testsuite, which checks the generated C output. We also have to add integration tests that will test:

* [x] actually compiling the C code via a C compiler
* [x] linking multiple files
* [ ] testing the C interop (call into C, callback from C, etc.)
* [ ] testing importing C header files (#541)

We probably can extend our current test framework, to test llvm and/or C with the same test files. We have to add the ability to specify other C files to compile and link.

I think the frontend should be improved to be able to use syntax like:
```
lpython --backend=c -c some_file.py -o some_file.c
```
Then we compile everything with gcc or clang.

**Comment by certik** [comment]
See also #542.

**Comment by Smit-create** [comment]
This seems to be fixed now.

**Comment by certik** [comment]
Only the first bullet point is fixed, the other three we still have to fix.

**Comment by certik** [comment]
The `./run_tests.sh` script now tests everything, and I moved the remaining two tasks above to #545, so I am going to close this one.
