### ISSUE TITLE
Manipulating C pointers

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#546]
Here is an example of how pointers should be manipulated, in Fortran, Python, both should generate the same ASR, and the C backend should then generate the output below:

Fortran:

    type(c_ptr) :: queries
    integer(2), pointer :: x(:)         
    c_f_pointer(queries, x)
    c_loc(x(idx))       

Python:

    from ltypes import c_loc, c_p_pointer, CPtr, Pointer
    from typing import Annotate
    queries: CPtr
    x: Annotate[i16[:], Pointer]
    x = c_p_pointer(queries, i16)                      
    c_loc(x[idx])           
    
C output:

    void *queries;
    int16_t *x;
    x = (int16_t*)queries;
    &x[idx];

Also allow passing `void *` pointers as arguments to functions.

**Comment by certik** [comment]
To pass `void *` as function arguments, in Python:
```python
@ccaller
def f(A_void: CPtr, idx: i32) -> None:
    A: Annotate[i16[:], Pointer]   
    A = c_p_pointer(A_void, i16)
    g(c_loc(A[idx])                    
```
translates to C:
```c
void f(void *A_void, int32_t idx) {
    int16_t *A;
    A = (int16_t *) A_void;
    g(&A[idx])
```

**Comment by certik** [comment]
Note: I think `c_loc(x[idx])` will not work in CPython, since `x[idx]` will return an integer as a value, so we can't take pointer to it from inside `c_loc`. We'll have to use some syntax from https://docs.python.org/3/library/ctypes.html#pointers.

**Comment by certik** [comment]
Yes, that's fine, if it can be done.

**Comment by certik** [comment]
Most of these are fixed. The remaining issue is #609.

**Comment by Shaikh-Ubaid** [comment]
>can we do, c_p_pointer(queries, x)

Can this be done @certik , @czgdp1807 ? Probably not. I think `Python` does not allow/support updating a variable passed as argument.

**Comment by certik** [comment]
Right, Python does not support it.
