### ISSUE TITLE
Improving integrations tests

### ISSUE THREAD

**Issue by Smit-create** [lcompilers/lpython#577]
Since we have recently added multiple backend integration testing, there are some improvements needed as following:
1. It should rebuild from scratch every time we run the script.
2. It should clean up all the generated files before exiting.

cc @certik @czgdp1807

**Comment by certik** [comment]
I would probably leave the generated files, I found it very useful for debugging and to see what the C backend generates. But I would automatically clean it before running, currently I have to manually do `git clean -dfx` in the integration_test directory.

One option is to build it in a "build" directory, then all we need is to remove the build directory before a run. That will force to rebuild from scratch.

**Comment by czgdp1807** [comment]
I think in LFortran we do integration testing outside the source directory. So it should be able to do in LPython as well. The scene is that right now CMake doesn't use relative path to integration test files,

```bash
(lp) 19:30:59:~/lpython_project/lpython % cd ../build-lpython-llvm
(lp) 19:31:04:~/lpython_project/build-lpython-llvm % cmake -DKIND=llvm ../lpython/i
ntegration_tests


Configuration results
---------------------
C compiler      : /Library/Developer/CommandLineTools/usr/bin/cc
Build type: Debug
C compiler flags      : -g
Installation prefix: /usr/local
KIND: llvm
LPYTHON_RTLIB_DIR: /Users/czgdp1807/lpython_project/lpython/src/runtime/impure
LPYTHON_RTLIB_LIBRARY: /Users/czgdp1807/lpython_project/lpython/src/runtime/liblpython_runtime_static.a
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/czgdp1807/lpython_project/build-lpython-llvm
(lp) 19:31:20:~/lpython_project/build-lpython-llvm % make
[  1%] Generating bindc_01.o
Traceback (most recent call last):
  File "/Users/czgdp1807/lpython_project/lpython/src/bin/../runtime/lpython_parser.py", line 8, in <module>
    input = open(filename).read()
FileNotFoundError: [Errno 2] No such file or directory: 'bindc_01.py'
The command 'python /Users/czgdp1807/lpython_project/lpython/src/bin/../runtime/lpython_parser.py bindc_01.py bindc_01.pyC57BB51' failed.
make[2]: *** [CMakeFiles/bindc_01.dir/build.make:74: bindc_01.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:166: CMakeFiles/bindc_01.dir/all] Error 2
make: *** [Makefile:101: all] Error 2
```

**Comment by czgdp1807** [comment]
Can we close this?

**Comment by certik** [comment]
I think this is now fixed. If there are any bugs, we can open new issues.
