### ISSUE TITLE
Docs: Add links to other Python compilers

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#6]
Here is an initial list:

* https://transonic.readthedocs.io/en/latest/index.html
* https://seq-lang.org/
* https://cython.org/
* https://pythran.readthedocs.io/en/latest/
* https://numba.pydata.org/
* https://pytorch.org/
* https://github.com/google/jax
* https://www.weld.rs/
* https://cupy.dev/
* https://github.com/pyccel/pyccel
* https://github.com/Quansight-Labs/uarray

**Comment by Thirumalai-Shaktivel** [comment]
- https://doc.pypy.org/en/latest/
- https://nuitka.net/
- https://github.com/pyston/pyston
- https://github.com/jakeret/hope
- https://github.com/shedskin/shedskin
- https://github.com/google/grumpy
- https://www.jython.org/
- https://ironpython.net/
- http://pyjs.org/
