### ISSUE TITLE
Inconsistency in error messages ?

### ISSUE THREAD

**Issue by faze-geek** [lcompilers/lpython#673]
```
s = "abc"
s = s + 1          # Int type

semantic error: Type mismatch in binary operator; the types must be compatible
 --> try.py:8:9
  |
8 |     s = s + 1
  |         ^   ^ type mismatch (str and i32)


s = "abc"
s = s + 1.0        # Float type

semantic error: Type mismatch in binary operator; the types must be compatible
 --> try.py:8:9
  |
8 |     s = s + 1.0
  |         ^   ^^^ type mismatch (str and f64)


s = "abc"
s = s + complex(1,2)   # Complex type - error message not uniform with the above types

semantic error: Casting str to complex is not Implemented   # How is this str to complex casting anyways ?
 --> try.py:8:9
  |
8 |     s = s + complex(1,2)
  |         ^ 


```

**Comment by faze-geek** [comment]
Python error for reference is -
`TypeError: can only concatenate str (not "< D >") to str.     # Where D is the other data type used`

**Comment by certik** [comment]
Yes, the complex error message should be improved. If you add `--show-stacktrace`, you will get a C++ stacktrace where the error is emitted in LPython, so you can go ahead and fix it up to be consistent with the other error messages.

**Comment by anutosh491** [comment]
I just tried out this issue on main and I see that the error messages are all consistent . Maybe this issue can be closed ? @faze-geek

**Comment by faze-geek** [comment]
> Maybe this issue can be closed ? @faze-geek 

Sure !
