### ISSUE TITLE
Instead of offsetting indices, set dimensions correctly in variable type

### ISSUE THREAD

**Issue by czgdp1807** [lcompilers/lpython#683]
https://github.com/lcompilers/lpython/blob/4591db8b087577046f548d21097d8c8c23fcb2f7/src/lpython/semantics/python_ast_to_asr.cpp#L887-L896

https://github.com/lcompilers/lpython/blob/4591db8b087577046f548d21097d8c8c23fcb2f7/src/lpython/semantics/python_ast_to_asr.cpp#L866-L870

The above code is hackish and it becomes to keep track whether to offset the index by 1 in an optimisation pass or not. The reason of confusion is,

1. We are setting lower bound as `1` and upper bound as `size` in both Python and Fortran.
2. We offsetting indices by `1` only in Python.
3. We only have ASR while performing an optimisation pass. In Python we set lower and upper bounds same as Fortran but we offset index by 1 only in Python. Hence no clear differences between the two.

I suggest doing the following,

1. Set lower bound as `0` and upper bound as `size - 1` in Python. In Fortran its provided by the user and default setting in LFortran is correct.
2. Don't offset indices by `1` in any LCompiler.
3. In an optimisation pass set the bounds of the loop (which we are creating manually in an optimisation pass) always to `0 + lower_bound(dimension)` and `size - 1 + lower_bound(dimension)`. In Python `lower_bound(dimension)` is always `0`, so no worries. In Fortran `lower_bound(dimension)` is by default `1` so loop bounds will transform to `1` and `size` automatically.

I discovered this problem while working on #675 and I can fix it in #675 itself.

@certik Please let me know what you think.

**Comment by certik** [comment]
See also: https://gitlab.com/lfortran/lfortran/-/issues/666

As discussed there, I think we should move to `(size, start_index)` representation of arrays. I don't have an opinion whether we should get rid of `start_index`, which would mean adjusting/offsetting all array indexing (there are pros/cons of doing that). So first let's keep the `start_index`. We should not offset any indices (that's the whole point of storing `start_index` in the first place).

**Comment by czgdp1807** [comment]
Well, my main concern is offsetting indices. Either you always do it in an optimisation pass or you never do it because once an ASR is formed you never know whether the source was Python or Fortran. So offsetting indices should never be done in any frontend irrespective of which array representation we are using. 

Anyways would it be okay if I remove offsetting indices by 1 in LPython? Let me know.

**Comment by certik** [comment]
Yes, we should not offset indices in array indexing. So yes, please remove any such code.

**Comment by czgdp1807** [comment]
Great. I slept on it. I think it won’t be good idea to do it in #675 as it will be out of context. I will do it in a subsequent PR.
