### ISSUE TITLE
Fails: Error while passing python pointer in function args

### ISSUE THREAD

**Issue by Smit-create** [lcompilers/lpython#690]
Python code:
```py
from ltypes import pointer, i16, Pointer

def g(x: Pointer[i16[:]]):
    y: i16[2]
    y[0] = 1
    y[1] = 2
    x = pointer(y)
    print(x[0], x[1])

def f():
    yptr1: Pointer[i16[:]]
    g(yptr1)

f()
```

**Comment by certik** [comment]
We have to decide what the semantics of this should be. It needs to be automatically dereferenced. Fortran automatically dereferences pointers, you use them like regular integers (in this case), just the declaration has the extra `Pointer` attribute. It seems like a good design, and we can probably do the same in LPython, if it can be done in both LPython and CPython with the same syntax (I am unsure if that is the case, we have to try and see).
