### ISSUE TITLE
Installation instructions for ssh, vpn, headless servers

### ISSUE THREAD

**Issue by rebcabin** [lcompilers/lpython#720]
On ssh, vpn, and headless servers, we can't install conda via a web page. I suggest something like the following

`wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh`

and something similar for other platforms

**Comment by certik** [comment]
Good point.

Here is a way to install it completely unattended: https://gitlab.com/lfortran/ci-images/-/blob/master/full/Dockerfile#L33, copying here (it will not ask any questions, and just install conda):
```bash
wget --no-check-certificate https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
bash miniconda.sh -b -p $HOME/conda_root
rm miniconda.sh
export PATH="$HOME/conda_root/bin:$PATH"
conda config --set always_yes yes --set changeps1 no
conda info -a
conda update -q -n root conda
```
Then one can use it like this:
```bash
conda install -c conda-forge python=3.8 pytest cmake ninja llvmdev=11.0.1
```
