### ISSUE TITLE
Add support for loop iteration

### ISSUE THREAD

**Issue by Madhav2310** [lcompilers/lpython#732]
Python Code: 
```
s: str
s = "samplestring"
char : str

for char in s:
    if ord(char) >= 97 and ord(char) <=122 :
        result += chr(ord(char) - 32)
    else :
        result += char
```

Error:
```
semantic error: Only function call `range(..)` supported as for loop iteration for now
   --> /home/madhav/lpython/src/runtime/lpython_builtin.py:156:5 - 160:26
    |
156 |        for char in s:
    |        ^^^^^^^^^^^^^^...


```

**Comment by Madhav2310** [comment]
It is supported for lists i think, not totally sure. https://github.com/lcompilers/lpython/blob/4591db8b087577046f548d21097d8c8c23fcb2f7/src/runtime/ltypes/ltypes.py#L76

**Comment by Madhav2310** [comment]
@certik @czgdp1807 @namannimmo10

**Comment by namannimmo10** [comment]
Similar to #206.

**Comment by Madhav2310** [comment]
> Similar to #206.

Right, yes. Who can I discuss with on how to implement this?

**Comment by czgdp1807** [comment]
What I would do here is, convert the following,

```python
for char in s:
    if ord(char) >= 97 and ord(char) <=122 :
        result += chr(ord(char) - 32)
    else :
        result += char
```

to,

```python
for i in range(len(s)):
    char = s[i]
    if ord(char) >= 97 and ord(char) <=122 :
        result += chr(ord(char) - 32)
    else :
        result += char
```

We can do it simply in the AST to ASR transition itself (in the node below). However we won't be able to get back the original code after this (AST to Source code transition).

https://github.com/lcompilers/lpython/blob/989b0a2c5442e4b0452ff0cdaf3b87ed872058bf/src/lpython/semantics/python_ast_to_asr.cpp#L2605-L2687

@certik @Madhav2310 What do you think?

**Comment by Madhav2310** [comment]
I don't understand the bit about AST to ASR transition, I'll look into it! But yes I'll go ahead and implement the python code that way to implement iterate over the strings. Thank you!
