### ISSUE TITLE
Assignment to multiple targets not supported

### ISSUE THREAD

**Issue by awfeequdng** [lcompilers/lpython#928]
when i assign multiple targets like this:
```
a, b = c = 2, 1
```
some error show like this:
```
semantic error: Assignment to multiple targets not supported
```
<img width="596" alt="image" src="https://user-images.githubusercontent.com/8253416/183240718-fcae642d-2745-4bcd-bf6c-05f78ffc7328.png">

**Comment by awfeequdng** [comment]
another error:
<img width="597" alt="image" src="https://user-images.githubusercontent.com/8253416/183240810-ef891f75-2361-4440-8fbb-dfc2dc4a5e3a.png">

**Comment by Thirumalai-Shaktivel** [comment]
Thanks @awfeequdng for reporting the issues.
For now, LPython is statically typed in Python files, so please declare the variable before using.
```py
$ cat examples/expr2.py
from ltypes import i32, f64

def main():
    a: i32
    b: i32
    c: i32
    a, b, c = 1, 2, 3
    print(a, b, c)

main()
$ lpython examples/expr2.py && ./a.out
1 2 3
```

**Comment by Thirumalai-Shaktivel** [comment]
Regarding the `Multiple target assignment`: Yup, it is an issue. We need to fix it.

**Comment by certik** [comment]
Thanks @awfeequdng for reporting the issue. We have to implement multiple assignments.
